### ISSUE TITLE
procmail routing

### ISSUE THREAD

**Issue by perler** [juanluisbaptiste/docker-otrs#102]
We want to switch to mail routing via procmail according to https://doc.otrs.com/doc/manual/admin/6.0/en/html/email-settings.html#procmail-queue-routing 

is this possible with the docker images and is there some documentation for this?

**Comment by juanluisbaptiste** [comment]
Hi @perler , currently is not possible, PR welcome.

**Comment by perler** [comment]
ok, I am thinking about how to do this in general and welcome input. the reason why this may be a bit more urgent for other users as well is, that email fetching with pop3 is getting more and more difficult with cloud bases services as google workspace and office 365 which phase out pop3/imap for oauth based authentication.

so, we have two containers, smtp (postfix) and otrs. what otrs expects is an smtp server which pipes the emails via procmail to $SYS_HOME/bin/otrs.Console.pl. as far as I know you cannot pipe between servers. I see three options:

1. moving the smtp server to the otrs container (at least optionally)
2. creating some kind of daemon who listens for the procmail pipes from the smtp container on the otrs container. the obvious "daemon" is postfix, go to 1 ;)
3. quick and dirty: add a pop3 server (dovecot) to the postfix container and hold the mails locally for fetching from the otrs container. this way there is no need to pop3 authenticate with the cloud services anymore, we can authenticate with the postfix container.

@juanluisbaptiste do you have an opinion/idea?

**Comment by juanluisbaptiste** [comment]
Installing a smtp server in the OTRS container is not an option, the idea of containerized applications is that they should do only one function. You should use a container for the specific function you need, a mail server container that downloads the emails in whatever form you need and then feeds them to the otrs container, for example via pop3/imap.

**Comment by perler** [comment]
ok, just a sidenote, the German documentation declares, that the procmail method is the preferred method, so this might be an issue in the future.

I have some trouble following the SMTP configuration in your OTRS image. We have (quite a long time ago) installed the otrs and smtp image with docker-compose as described here. But I am actually not quite clear which path the mail takes. We have OTRS configured to use SMTP as mail transport, but the mail server points to the OTRS

**Comment by juanluisbaptiste** [comment]
The SMTP server used on the compose file is only for sending email, you can look at that [project documentation](https://github.com/juanluisbaptiste/docker-postfix) for more details. I don't understand what you mean with which path the email will take, also why is the mail server pointing to OTRS ? I do not understand this either.

**Comment by perler** [comment]
Sorry, I sent this  comment by accident. It was a brain fart. what we are going  to do is replace your SMTP container with a full-fledged mail server with postfix and this will solve our problems.

**Comment by juanluisbaptiste** [comment]
Ahh ok, yes, the best solution on this case is to use a mail server that can retrireve the email instead of OTRS and then feed it to it with procmail.

**Comment by perler** [comment]
this on the other hand will not work as procmail needs to run inside the
otrs container. but we will forward mail for otrs from office365 (which
lacks proper pop3 support) to the postfix/dovecot container and fetch it
from there with otrs pop3 import..

**Comment by juanluisbaptiste** [comment]
If you mean running a smtp server inside the docker container, then no, it was already explained before [why](https://github.com/juanluisbaptiste/docker-otrs/issues/102#issuecomment-737557029).
