### ISSUE TITLE
Changing Timezone to other than UTC corrupts code.

### ISSUE THREAD

**Issue by gs4711** [juanluisbaptiste/docker-otrs#112]
Whenever we're changinfg the OTRS_TIMEZONE from UTC to another value, i.e. MET, many warnings appear:

otrs_1     | Deep recursion on subroutine "Kernel::System::ObjectManager::Create" at /opt/otrs/Kernel/System/Log.pm line 190.
otrs_1     | Deep recursion on subroutine "Kernel::System::ObjectManager::_ObjectBuild" at /opt/otrs/Kernel/System/ObjectManager.pm line 242.
otrs_1     | Deep recursion on subroutine "Kernel::System::DateTime::new" at /opt/otrs/Kernel/System/ObjectManager.pm line 307.
otrs_1     | Deep recursion on subroutine "Kernel::System::DateTime::_CPANDateTimeObjectCreate" at /opt/otrs/Kernel/System/DateTime.pm line 153.
otrs_1     | Deep recursion on subroutine "Kernel::System::Log::Log" at /opt/otrs/Kernel/System/DateTime.pm line 1831.
otrs_1     | Use of uninitialized value in lc at /opt/otrs/bin/otrs.Daemon.pl line 576.
otrs_1     | Killing Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager with PID 282
otrs_1     | Jul 13 17:35:01 e03ff352cd2a CROND[306]: (otrs) CMD ($HOME/bin/otrs.Daemon.pl start >> /dev/null)
otrs_1     | Deep recursion on subroutine "Kernel::System::ObjectManager::Create" at /opt/otrs/Kernel/System/Log.pm line 190.
otrs_1     | Deep recursion on subroutine "Kernel::System::ObjectManager::_ObjectBuild" at /opt/otrs/Kernel/System/ObjectManager.pm line 242.
otrs_1     | Deep recursion on subroutine "Kernel::System::DateTime::new" at /opt/otrs/Kernel/System/ObjectManager.pm line 307.
otrs_1     | Deep recursion on subroutine "Kernel::System::DateTime::_CPANDateTimeObjectCreate" at /opt/otrs/Kernel/System/DateTime.pm line 153.
otrs_1     | Deep recursion on subroutine "Kernel::System::Log::Log" at /opt/otrs/Kernel/System/DateTime.pm line 1831.
otrs_1     | Deep recursion on subroutine "Kernel::System::ObjectManager::Create" at /opt/otrs/Kernel/System/Log.pm line 190.
otrs_1     | Deep recursion on subroutine "Kernel::System::ObjectManager::_ObjectBuild" at /opt/otrs/Kernel/System/ObjectManager.pm line 242.
otrs_1     | Deep recursion on subroutine "Kernel::System::DateTime::new" at /opt/otrs/Kernel/System/ObjectManager.pm line 307.
otrs_1     | Deep recursion on subroutine "Kernel::System::DateTime::_CPANDateTimeObjectCreate" at /opt/otrs/Kernel/System/DateTime.pm line 153.
otrs_1     | Deep recursion on subroutine "Kernel::System::Log::Log" at /opt/otrs/Kernel/System/DateTime.pm line 1831.

**Comment by juanluisbaptiste** [comment]
@gs4711 you completely skipped the information asked but the bug report wizard, it is asked for a reason. Please provide it if you want this issue investigated.

**Comment by gs4711** [comment]
Thanks for your note, @juanluisbaptiste !

The host environment is a `CentOS Linux release 7.9.2009 (Core)`, with Docker version 20.10.7, build f0df350

As soon as I had changed the default timezone by setting `OTRS_TIMEZONE` within the file `.env ` to a value other than `UTC`, the mentioned error messages appear.

**Comment by rdxmb** [comment]
```
OTRSTimeZone

    Sets the time zone being used internally by OTRS to e. g. store dates and times in the database. WARNING: This setting must not be changed once set and tickets or any other data containing date/time have been created.
```

from https://doc.otrs.com/doc/manual/admin/6.0/en/html/ConfigReference_Section_Core_Time.html

So I don't think this is a container bug.
