### ISSUE TITLE
Docker hub seems empty ...

### ISSUE THREAD

**Issue by rdxmb** [juanluisbaptiste/docker-otrs#114]
https://hub.docker.com/u/juanluisbaptiste

do you know what's going on here?

**Comment by rdxmb** [comment]
hm, this is only the case when I am logged in. 

![Screenshot_20210914_170738](https://user-images.githubusercontent.com/30314040/133283594-f5b2162f-bbef-4eac-be39-fca2637e546e.png)

![Screenshot_20210914_170808](https://user-images.githubusercontent.com/30314040/133283659-31a772f1-8fb3-4524-99b4-71d1ba723861.png)

Strange. So I close this.

**Comment by juanluisbaptiste** [comment]
@rdxmb maybe a temporal issue with hub ? I can see that repo both when logged in and not logged in.

**Comment by rdxmb** [comment]
This seems to be the effect when the email-address is not validated 🤷
