### ISSUE TITLE
Setting OTRS_DISABLE_EMAIL_FETCH=no does not re-enable email fetching

### ISSUE THREAD

**Issue by dawtmaytrikx** [juanluisbaptiste/docker-otrs#116]
Using the znuny_6_0_x branch, with Znuny 6.0.33.

**Describe the issue**
I imported my database and initially set `OTRS_DISABLE_EMAIL_FETCH=yes` in the .env file just to make sure everything worked before I pulled the emails from the server. After setting the above mentioned variable to `no` or commenting it out and restarting the container, email fetching was still disabled though. Email fetching was only re-enabled after manually activating `Daemon::SchedulerCronTaskManager::Task###MailAccountFetch` in the system config.

**Expected behavior**
Setting `OTRS_DISABLE_EMAIL_FETCH=no` or commenting it out should re-enable email fetching.

**Comment by juanluisbaptiste** [comment]
The issue is that only the disabling of the email fetch is implemented, but but not the other way around. I will fix this ASAP.

**Comment by juanluisbaptiste** [comment]
Please test and reopen if you still have any issues.

**Comment by juanluisbaptiste** [comment]
> Using the znuny_6_0_x branch, with Znuny 6.0.33.
> 
Also, this branch for now is not being updated, only master. It was used when testing the migration to Znuny but when testing finished master was updated with the changes of that branch and development continues there.

Later on znuny_6_0_x will host the LTS release and master will become the new development branch with the 6.1.x release (when I have time to work on this).
