### ISSUE TITLE
provide Ubuntu 20.04 LTS image for otrs?

### ISSUE THREAD

**Issue by dpalic** [juanluisbaptiste/docker-otrs#119]
hi there,

I am interested in running otrs on ubuntu 20.04 instead of the dead centos7

Are you having plans to provide the image?
If yes, what timeframe?
If no, would you accept a pull request?

Also wondering if you have plans to get support on adding ubuntu support to znuny image?

**Comment by juanluisbaptiste** [comment]
Hi @dpalic, switching the base OS is not an easy task and we will not provide such image.
