### ISSUE TITLE
OTRS_HOSTNAME

### ISSUE THREAD

**Issue by gusmoreto** [juanluisbaptiste/docker-otrs#122]
I want to put a DNS on OTRS_HOSTNAME, with HTTPS protocol

**Comment by juanluisbaptiste** [comment]
As the new issue instructions that you clearly ignored say:

This is **not** a problem reporting forum, only report if you are pretty sure what you are experiencing is a bug with this image _and_ docker, not a configuration issue of OTRS, for that you can use the [Github discussions section](https://github.com/juanluisbaptiste/docker-otrs/discussions).
