### ISSUE TITLE
Build failed because file credentials-smtp.env is missing

### ISSUE THREAD

**Issue by kler** [juanluisbaptiste/docker-otrs#13]
File `credentials-smtp.env` is missing, so project won't build from a fresh checkout.

    $ docker-compose build
    ERROR: Couldn't find env file: /home/user/credentials-smtp.env

**Comment by juanluisbaptiste** [comment]
Please read de complete README on instructions about that file.

**Comment by kler** [comment]
Please add some info about `credentials-smtp.env` in de README, and I'll read it.

    $ curl -s https://raw.githubusercontent.com/juanluisbaptiste/docker-otrs/master/README.md | grep -i credentials-smtp.env || echo "Incomplete readme"
    Incomplete readme

**Comment by juanluisbaptiste** [comment]
Don't be lazy and fully read it, it says this:

This command will build all the images and pull the missing ones like the SMTP relay. This SMTP relay container has its own configuration, you need to specify the environment variables for the SMTP account that will be used to send OTRS email notifications. Please take a look at the documentation.

**Comment by kler** [comment]
I've been a part of the open source community since the last millennia.
I consider it good practice to 1) have clear documentation, and 2) keep a good tone.

By saying **"Please read de complete README on instructions about that file."** you *imply* that I haven't read it. I have, several times. Problem is that the README doesn't *contain* any information about that file. So instead I need understand this whole chain of stuff *(ah, it's something about smtp, ah, **something** should go inte this file, ah, probably bash style environments, or?, ah, lots of `../..` guess that's evaluates to the root or something)* which could easily have been put in a sentence.

Imagine you yourself for the first time thought about trying OTRS out, you google `otrs docker-compose`. I think you also would have thought your own package would have room for improvements.

So back to the problem. docker-compose complains about a file which doesn't exist and is not mentioned anywhere in the README. I'll surely figure this out eventually, but that's far from optimal. I assume many people that find their way to your project are looking to either 1) try OTRS out, or 2) have a recipe for running OTRS in some production environment. Members of group 1 will certainly appreciate if the software started without any manual intervention. I'm a strong believer of convention over configuration.

Why not just add information to the README? Or even better, just strive to have a docker-compose.yaml that runs out of the box. `git checkout repo && docker-compose up`. There are such fake smtp servers as maildev for instance (which provides both an SMTP server and also a web interface to view sent mails). I would definitely go for that as default.

**Comment by kordianbruck** [comment]
@kler did you figure out how to create that file correctly? I'm banging my head here.
Is it that you just simply run the relay docker image as well? Or can I just supply some login data?
An example would be just great.

**Comment by juanluisbaptiste** [comment]
@kordianbruck can you just read the documentation that I have kindly written ?? on the main README file says:

> This command will build all the images and pull the missing ones like the SMTP relay. This SMTP relay container has its own configuration, you need to specify the environment variables for the SMTP account that will be used to send OTRS email notifications. Please take a look at the [documentation](https://github.com/juanluisbaptiste/docker-postfix).

**Comment by kordianbruck** [comment]
@juanluisbaptiste its really not clear to my, why exactly I would need to run an extra relay? OTRS can directly connect to remote SMTP / IMAP servers?

**Comment by juanluisbaptiste** [comment]
The idea is to simplify configuration so you don't need to put SMTP configuration on OTRS but use an external relay that can be used by other containers.

**Comment by kler** [comment]
@kordianbruck I abandoned this project because of the unfriendly and arrogant conversation climate.

**Comment by kordianbruck** [comment]
```
The idea is to simplify configuration so you don't need to put SMTP configuration on OTRS but use an external relay that can be used by other containers.
```
Good Idea, but is there any way to make it optional? I'd rather just conf the system itself :+1: 

```
@kordianbruck I abandoned this project because of the unfriendly and arrogant conversation climate.
```
I see - well it certainly could be improved, but its up to both parties to do that. Anyway, yes as this particular question already poped up multiple times, it certainly could use some improvement in the docs. 

After all juan is offering this worktime and effort for free - you shouldn't have any expectations. One could just open up a PR for example. (Often its even worse and the maintainer does not reply at all)

**Comment by juanluisbaptiste** [comment]
> Good Idea, but is there any way to make it optional? I'd rather just conf the system itself 👍

It can, but not using the environment variables, you could remove the postfix definition and link from the docker-compose file, fire it up and configure the _SendmailModule_ parameters as you need.

> After all juan is offering this worktime and effort for free - you shouldn't have any expectations. One could just open up a PR for example. (Often its even worse and the maintainer does not reply at all)

Thanks, at least some people understand how open source _contributions_ work.

**Comment by kordianbruck** [comment]
@juanluisbaptiste ah, yea thats sounds great. Will try that out and open a PR for a compose file without the dependancy if you want 🤘

**Comment by juanluisbaptiste** [comment]
@kordianbruck no because I'm not going to change the way it currently works. The PR must allow to both configurations to be allowed and configured using environment variables. 

If not then any user can just remove the postfix container and link and configure OTRS as they want.

**Comment by kler** [comment]
> After all juan is offering this worktime and effort for free - you shouldn't have any expectations

I don't know about you, but I always expect polite answers.

**Comment by kordianbruck** [comment]
@juanluisbaptiste I see, this all makes perfect sense now. Thanks for providing this image - works like a charm, once you figure out the little nags. Keep it up :+1:

**Comment by lucaspottersky** [comment]
just for your information, i've just bumped into the same issue.

if somebody else is reading this and don't want to waste time like i did here's what you should do:

```
cd docker-otrs
vim ../../credentials-smtp.env
```

<< CONFIGURATION, EXAMPLE: >>
```
SMTP_SERVER=smtp.bar.com
SMTP_PORT=25
SMTP_USERNAME=foo@bar.com
SMTP_PASSWORD=YOUR_PASSWORD_HERE
SERVER_HOSTNAME=helpdesk.mycompany.com
```

@juanluisbaptiste coule we perhaps include a sample like this other project does https://github.com/helpyio/helpyio-docker/blob/master/.env.sample ?

**Comment by juanluisbaptiste** [comment]
@lucaspottersky the README is very clear on that you need to checkout the smtp relay coontainer page if you plan to use it (there's a link too) to see what variables you need to set.

If you want an example file, PR is welcome.
