### ISSUE TITLE
Build fails: Cannot link to a non running container

### ISSUE THREAD

**Issue by kler** [juanluisbaptiste/docker-otrs#14]
After commenting out the following lines in `docker-compose.yaml` since they are failing, the container won't start.

Commenting out from `docker-compose.yaml`:

    env_file: ../docker-otrs/otrs-setup.env

And:

    env_file: ../../credentials-smtp.env

Error occurs when trying to build:

    $ docker-compose up
    [...]
    WARNING: Image for service otrs was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
    Creating dockerotrs_data-otrs_1
    Creating dockerotrs_postfix_1
    Creating dockerotrs_data_1
    Creating dockerotrs_mariadb_1
    Creating dockerotrs_otrs_1
    
    ERROR: for otrs  Cannot start service otrs: Cannot link to a non running container: /dockerotrs_mariadb_1 AS /dockerotrs_otrs_1/dockerotrs_mariadb_1
    ERROR: Encountered errors while bringing up the project.

**Comment by juanluisbaptiste** [comment]
Please read the README file for instructions on that file and please don't create duplicated issues.

**Comment by kler** [comment]
I've read the README, several times. Didn't help.
I didn't create any duplicate issues, since there were no issues open at the time of my reports.
