### ISSUE TITLE
OTRS not accessible on given port

### ISSUE THREAD

**Issue by redrick** [juanluisbaptiste/docker-otrs#16]
I am trying to run the image, went through docs, the only thing I left out if SMTP because even with proper configs it given me `exit code 1`, but I think It does not play a role in my problem...

OTRS starts correctly and I see it processing over time in the log when run locally with:

```
sudo docker-compose -f docker-compose-prod.yml up
```

my problem is that OTRS is not accessible on `http://localhost:80`

I made sure nothing is using that port.... Even when trying to remap ports in `docker-compose-prod` file it is not accessible...

I was also looking at `docker ps` what is the port and it is as desired, but when trying to load nothing appears there....

any ideas where this may originate ?

NOTE: for me is good enough it would be accessible like this on localhost, I only want to use it for local testing of library using its JSON API, so no need for `-d` detached run or some such... 

Thanks 😃

**Comment by juanluisbaptiste** [comment]
It's probably a problem with the volume permissions. Please delete their contents and verify permissions are set as described on the README, delete old containers and volumes and start the container up.

If this doesn't work please set OTRS_DEBUG=yes and post the startup output here (if it's very large please use pastebin).

**Comment by redrick** [comment]
ok not working for me and OTRS_DEBUG=true is free of fails which is a bit odd, but not to waste any more of your time we ended up creating OTRS with docker on ubuntu with PostgreSQL, tailored just for our testing, but thanks for your reply :)
