### ISSUE TITLE
OTRS 5 Support

### ISSUE THREAD

**Issue by frennkie** [juanluisbaptiste/docker-otrs#2]
Any plans of building docker containers with OTRS version 5?

**Comment by juanluisbaptiste** [comment]
Almost done, see https://github.com/juanluisbaptiste/docker-otrs/tree/otrs-5_0_x branch. I'm just missing some tests with the backup and restore scripts, and some other little details.

**Comment by frennkie** [comment]
Sorry, I hadn't checked the branches.. but great to hear this! :+1:  :-)
I'll try to check it out later this week (hopefully).

**Comment by frennkie** [comment]
The reason why I came across this repo is that I'm working on a Python wrapper for the OTRS HTTP:REST API. In order to set up some decent tests I needed exactly this docker-otrs image.. :-) !
I added the few lines that are required to add the Web Service in a separate branch in my fork. Would you be interested in this? Should I send a PR?
https://github.com/frennkie/docker-otrs/tree/add-webservice

**Comment by juanluisbaptiste** [comment]
Sure why not :)

**Comment by juanluisbaptiste** [comment]
Still interested on doing that PR ? :-)
