### ISSUE TITLE
Update OTRS 5.0.26-01 or maybe 6

### ISSUE THREAD

**Issue by DookiEfromMoon** [juanluisbaptiste/docker-otrs#22]
Is it possible?

**Comment by drahkrub** [comment]
OTRS 6 would be cool

**Comment by juanluisbaptiste** [comment]
I'm almost finished with the OTRS 6 image, but for upgrade from 5.x you will need to follow official instructions. I have been planning on automating that too but haven't had the time.

**Comment by juanluisbaptiste** [comment]
I'm sorry, I misread the issue's subject: yes, I will also update the OTRS 5 image to 5.0.26 (additional to OTRS 6 image).

**Comment by DookiEfromMoon** [comment]
Thank you 👍

**Comment by juanluisbaptiste** [comment]
Here's a preview of the OTRS 6 image so you can help me test it if you want:

https://github.com/juanluisbaptiste/docker-otrs/tree/otrs-6_0_x

I still haven't pushed images to docker hub, I'll plan to do it later after I finish testing everything at least once.

**Comment by juanluisbaptiste** [comment]
ok, I have pushed a beta image, you can use juanluisbaptiste/otrs:6beta to check it out.

**Comment by juanluisbaptiste** [comment]
I have pushed an updated version, everything seems to be working fine (installer,normal startup, backup/restore). 

The only issue I'm facing is with sending emails. SMTP configuration is Ok, you can telnet to postfix:25 and get a port open, when sending an email (for ex, a new ticket) the popup closes without errors and and a message saying that the message has been queued for sending and a spining wheel on the VIA column on the ticket's messages list, and no errors on log files. This looks like an external issue but I can find any references anywhere.

@DookiEfromMoon , @drahkrub could you please give it a try ?

**Comment by DookiEfromMoon** [comment]
Hey, 

i can give it a try on the weekend.

**Comment by juanluisbaptiste** [comment]
I released today, you can read more about the new features [here](http://not403.blogspot.com.co/2018/02/otrs-6-help-desk-system-on-docker.html).
