### ISSUE TITLE
OTRS_ROOT_PASSWORD vs MYSQL_ROOT_PASSWORD

### ISSUE THREAD

**Issue by politsin** [juanluisbaptiste/docker-otrs#25]
in DOCS:
OTRS_ROOT_PASSWORD root@localhost user password. Default password is changeme
in CODE:
```sh
  while [ ! "$(mysqladmin ping -h ${OTRS_DB_HOST} -P ${OTRS_DB_PORT} -u root \
              --password="${MYSQL_ROOT_PASSWORD}" --silent --connect_timeout=3)" ]; do
```
https://github.com/juanluisbaptiste/docker-otrs/blob/master/otrs/functions.sh#L51

**Comment by juanluisbaptiste** [comment]
And your point being what ? both password are differenT, MYSQL_ROOT_PASSWORD is the MySQL root password, OTRS_ROOT_PASSWORD is OTRS root@localhost user password. 

Read the docs carefully.
