### ISSUE TITLE
Database Server is not available

### ISSUE THREAD

**Issue by masterheese** [juanluisbaptiste/docker-otrs#27]
Hey Dude, 

hope you can help me out, maybe i´m just to stupid . 

When i´m starting my Database OTRS is saying database server is not avaible 

Output is:

sh-4.2$ sudo docker-compose -f docker-compose.yml up
Creating dockerotrs_mariadb_1
Creating dockerotrs_otrs_1
Attaching to dockerotrs_mariadb_1, dockerotrs_otrs_1
mariadb_1  | 180319 13:57:07 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
mariadb_1  | 180319 13:57:07 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
otrs_1     | [INFO] Database server is not available. Waiting 2 seconds...
otrs_1     | [INFO] Database server is not available. Waiting 2 seconds...

I Will attach you my docker-compose.yml file, hope you can help me
[docker-compose.txt](https://github.com/juanluisbaptiste/docker-otrs/files/1825041/docker-compose.txt)

Permissions on the Volumes are set 

Best Regards

Masterheese

**Comment by masterheese** [comment]
otrs_1     | [INFO] Database server is not available. Waiting 2 seconds...
otrs_1     | + '[' '!' '' ']'
otrs_1     | + print_info 'Database server is not available. Waiting 2 seconds...'
otrs_1     | + echo -e '\e[46m[INFO]\e[0m Database server is not available. Waiting 2 seconds...'
otrs_1     | + sleep 2

**Comment by masterheese** [comment]
As far as i can see, this is because he tries to ping the Hostname but when i look in the Container he doesn´t change the Hostname and he recieves the Container ID as Hostname.

**Comment by masterheese** [comment]
Wrong track, the DB Password was not passthrough , through the Variable. 

Fixed it

**Comment by houstek** [comment]
Hi,
I have the same problem and the documentation is not very clear on this subject. What exactly did you do?

**Comment by juanluisbaptiste** [comment]
The documentation is clear, review if the database volume owner is correct (27) before starting the service.

**Comment by houstek** [comment]
I know that you spent a lot of time to give this image and the documentation, and I thank you for it, but of my point of view it is indistinct on certain points.
I opened an issue concerning the problem which I meet [https://github.com/juanluisbaptiste/docker-otrs/issues/28](url)
