### ISSUE TITLE
[INFO] Database server is not available. Waiting 2 seconds. 

### ISSUE THREAD

**Issue by miaohf** [juanluisbaptiste/docker-otrs#29]
root@NAS:~# docker inspect juanluisbaptiste-otrs1
[
    {
        "Id": "a7c276f1dba5cf61496751bcc3274261450ecbf9b45e407fb93fd9ccc2723540",
        "Created": "2018-05-19T06:04:25.058168702Z",
        "Path": "/run.sh",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-05-20T10:59:45.714163253Z",
            "FinishedAt": "2018-05-20T11:11:10.96189853Z",
            "StartedTs": 1526813985,
            "FinishedTs": 1526814670
        },
        "Image": "sha256:2eb9b6232849f3dc95d426e9ce129003e3e66f9a6053ec3e8184929675e28775",
        "ResolvConfPath": "/volume1/@docker/containers/a7c276f1dba5cf61496751bcc3274261450ecbf9b45e407fb93fd9ccc2723540/resolv.conf",
        "HostnamePath": "/volume1/@docker/containers/a7c276f1dba5cf61496751bcc3274261450ecbf9b45e407fb93fd9ccc2723540/hostname",
        "HostsPath": "/volume1/@docker/containers/a7c276f1dba5cf61496751bcc3274261450ecbf9b45e407fb93fd9ccc2723540/hosts",
        "LogPath": "/volume1/@docker/containers/a7c276f1dba5cf61496751bcc3274261450ecbf9b45e407fb93fd9ccc2723540/log.db",
        "Name": "/juanluisbaptiste-otrs1",
        "RestartCount": 0,
        "Driver": "btrfs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "db",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": ""
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Env": [
                "OTRS_INSTALL=yes",
                "OTRS_LANGUAGE=en",
                "OTRS_ROOT_PASSWORD=changeme",
                "OTRS_DB_PORT=33306",
                "OTRS_DB_HOST= 192.168.3.210",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "OTRS_VERSION=6.0.6-01",
                "OTRS_ROOT=/opt/otrs/",
                "OTRS_BACKUP_DIR=/var/otrs/backups",
                "OTRS_CONFIG_DIR=/opt/otrs/Kernel",
                "OTRS_CONFIG_MOUNT_DIR=/config/",
                "SKINS_PATH=/opt/otrs//var/httpd/htdocs/skins/"
            ],
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 50,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": -1,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "juanluisbaptiste-otrs1",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "OTRS_INSTALL=yes",
                "OTRS_LANGUAGE=en",
                "OTRS_ROOT_PASSWORD=changeme",
                "OTRS_DB_PORT=33306",
                "OTRS_DB_HOST= 192.168.3.210",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "OTRS_VERSION=6.0.6-01",
                "OTRS_ROOT=/opt/otrs/",
                "OTRS_BACKUP_DIR=/var/otrs/backups",
                "OTRS_CONFIG_DIR=/opt/otrs/Kernel",
                "OTRS_CONFIG_MOUNT_DIR=/config/",
                "SKINS_PATH=/opt/otrs//var/httpd/htdocs/skins/"
            ],
            "Cmd": [
                "/run.sh"
            ],
            "ArgsEscaped": true,
            "Image": "juanluisbaptiste/otrs:6.0.6",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "build-date": "20180302",
                "license": "GPLv2",
                "name": "CentOS Base Image",
                "vendor": "CentOS"
            },
            "DDSM": false
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "1390a3c4736f295f177f226be7c29e478b0afd7a0e83990a5dce7a3a6b763f77",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/1390a3c4736f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "a363cbd561add56c5ae47c0f495941348936235cdd1f7ce6cc9d3951067bc45f",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]
root@NAS:~#

**Comment by miaohf** [comment]
![image](https://user-images.githubusercontent.com/10840733/40278347-52f44f8e-5c62-11e8-8a78-4217aad27c02.png)
![image](https://user-images.githubusercontent.com/10840733/40278356-7aa580a2-5c62-11e8-8149-4565f632e906.png)

**Comment by juanluisbaptiste** [comment]
The issue is volume permissions, please READ the README file.
