### ISSUE TITLE
OTRS_ROOT_PASSWORD is emty if not defined

### ISSUE THREAD

**Issue by mx03** [juanluisbaptiste/docker-otrs#30]
The readme says:
"`OTRS_ROOT_PASSWORD` root@localhost user password. Default password is `changeme`."

If OTRS_ROOT_PASSWORD is empty it uses DEFAULT_OTRS_PASSWORD, but the variable is nowhere defined, so the password is set to nothing instead to changeme.

**Comment by juanluisbaptiste** [comment]
Ooops, I think it got removed on a code refactoring. I'll fix it ASAP.
