### ISSUE TITLE
OTRS_DB_USER not used

### ISSUE THREAD

**Issue by ToastyBiggums** [juanluisbaptiste/docker-otrs#31]
functions.sh hardcodes the user as "root" and doesn't allow you to define an already created database.

**Comment by juanluisbaptiste** [comment]
What are you talking about ?

root is only used to create OTRS_DB_USER, and that variable IS used: 

```
function create_db() {
  print_info "Creating OTRS database..."
  $mysqlcmd -e "CREATE DATABASE IF NOT EXISTS ${OTRS_DB_NAME};"
  [ $? -gt 0 ] && print_error "Couldn't create OTRS database !!" && exit 1
  $mysqlcmd -e " GRANT ALL ON ${OTRS_DB_NAME}.* to '${OTRS_DB_USER}'@'%' identified by '${OTRS_DB_PASSWORD}'";
  [ $? -gt 0 ] && print_error "Couldn't create database user !!" && exit 1
}
```

**Comment by ToastyBiggums** [comment]
"doesn't allow you to define an already created database."

**Comment by juanluisbaptiste** [comment]
But you are talking about the db user too so ? write a proper issue description if you want help, I sill dont understand whats your point.
