### ISSUE TITLE
Wrong permissions of skins/*/css-cache

### ISSUE THREAD

**Issue by ponchofiesta** [juanluisbaptiste/docker-otrs#33]
We have a custom skin and everytime I restart the OTRS container the permissions on the skins css-cache folder is broken. I assume it is because you are running SetPermissions script in your run.sh. I'd assume OTRS would keep this in mind but for some reason the permission is broken in our skin.

Bad (after cotnainer restart):
```
[root@0d1edda79228 /]# cd /opt/otrs/var/httpd/htdocs/skins/Agent/ubsimple/
[root@0d1edda79228 ubsimple]# ll
total 16
drwxrwsr-x+ 2 otrs   apache 4096 Jun  6 16:13 css
drwxrwsr-x+ 2 otrs   apache 4096 Jun 12 10:11 css-cache
drwxrwsr-x+ 2 otrs   apache 4096 Apr 26 12:54 img
drwxrwsr-x+ 3 otrs   apache 4096 Jun  6 10:15 vendor
```

Good (after fixing the permissions manually):
```
[root@0d1edda79228 /]# cd /opt/otrs/var/httpd/htdocs/skins/Agent/ubsimple/
[root@0d1edda79228 ubsimple]# ll
total 16
drwxrwsr-x+ 2 otrs   apache 4096 Jun  6 16:13 css
drwxrwsr-x+ 2 apache apache 4096 Jun 12 10:11 css-cache
drwxrwsr-x+ 2 otrs   apache 4096 Apr 26 12:54 img
drwxrwsr-x+ 3 otrs   apache 4096 Jun  6 10:15 vendor
```

**Comment by ponchofiesta** [comment]
I assume you'll need `/opt/src/otrs/bin/otrs.SetPermissions.pl --web-group=www-data` without the user.

**Comment by juanluisbaptiste** [comment]
Hi,

How are you adding the new skin ? through a custom Dockerfile or mounting it ?

**Comment by ponchofiesta** [comment]
I've mounted it. Actually I use a Dockerfile to extend your image and it looks like this way the permission is OK. But I only tested it once

**Comment by juanluisbaptiste** [comment]
@ponchofiesta yes, that is how I do it too, by extending the Dockerfile, I have not tested it mounting it, I will try to take a look this weekend.

**Comment by juanluisbaptiste** [comment]
Hi,

Since some time now the image supports mounting the skins directory and mounted by default on the [docker-compose](https://github.com/juanluisbaptiste/docker-otrs/blob/master/docker-compose.yml) file. Could you test again ?

Thanks.

**Comment by ponchofiesta** [comment]
Thanks for that.
Using your image as base was working fine. I built my workflow around that. Now we have a Git repo with our customizations and build our own image on top of yours. So I cannot test the other way anymore.

**Comment by juanluisbaptiste** [comment]
Ok excellent, I'll close this then.
