### ISSUE TITLE
Make SendmailModule configurable

### ISSUE THREAD

**Issue by schadom** [juanluisbaptiste/docker-otrs#34]
Hello,

currently the `SendmailModule` settings are static in Kernel/Config.pm:
https://github.com/juanluisbaptiste/docker-otrs/blob/master/otrs/Config.pm#L96

It would be nice if those could be removed or overwritten with environment variables, for example we would like to use  `SendmailModule => 'Kernel::System::Email::SMTPTLS'` with custom settings from the DB.

The otrs config params are;

	SendmailModule
	SendmailModule::AuthUser
	SendmailModule::AuthPassword
	SendmailModule::Host
	SendmailModule::Port

Thanks

**Comment by juanluisbaptiste** [comment]
Currently that file is not being used, but indeed mail configuration is hard-coded in functions.sh. For now I do not plan to change this, but a PR is welcome.

**Comment by schadom** [comment]
Thanks. PR follows asap.

**Comment by juanluisbaptiste** [comment]
Fixed by #64
