### ISSUE TITLE
Postmaster mailboxe fetching is not working

### ISSUE THREAD

**Issue by schadom** [juanluisbaptiste/docker-otrs#35]
Using an existing otrs database, the postmaster mailbox fetch does not work.  The otrs daemon seems to connect to our IMAP-server with an empty username (`imap-login: Disconnected (no auth attempts in 0 secs): user=<>`) therefore the authentication fails.

When we use a fresh otrs installation on a VM with the same existing otrs-database, the IMAP fetch works without any problems. So the problem must be related to the docker image.

Thanks

**Comment by juanluisbaptiste** [comment]
I have at least 5 production installations with IMAPS configured, did one this week with the latest version and it is working too. Your problem must lie elsewhere.

**Comment by juanluisbaptiste** [comment]
Also using an external database is not supported ATM, I have never tested it.

**Comment by schadom** [comment]
>I have at least 5 production installations with IMAPS configured, did one this week with the latest version and it is working too. Your problem must lie elsewhere.
thanks, somehow changing from IMAPTLS to IMAPS fixed it.  funnily it's working for some, but not all mailboxes.

>Also using an external database is not supported ATM, I have never tested it.
works fine 👍
