### ISSUE TITLE
OTRS is starting but cant login

### ISSUE THREAD

**Issue by vibratim** [juanluisbaptiste/docker-otrs#38]
The container started successfully but i get these errors

`ERROR: OTRS-otrs.Daemon.pl - Daemon Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager-10 Perl: 5.16.3 OS: linux Time: Thu Aug 30 11:18:24 2018

Message: There was an error executing ConfigurationDeploySync: [Thu Aug 30 11:18:24 2018] otrs.Daemon.pl: DBD::mysql::st execute failed: Table 'otrs.sysconfig_deployment' doesn't exist at /opt/otrs/Kernel/System/DB.pm line 694.

ERROR: OTRS-otrs.Daemon.pl - Daemon Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager-10 Perl: 5.16.3 OS: linux Time: Thu Aug 30 11:18:24 2018`

Alongside with some of these

`ERROR: OTRS-otrs.Daemon.pl - Daemon Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager-10 Perl: 5.16.3 OS: linux Time: Thu Aug 30 11:18:24 2018

Message: There was an error executing ConfigurationDeploySync: [Thu Aug 30 11:18:24 2018] otrs.Daemon.pl: DBD::mysql::st execute failed: Table 'otrs.sysconfig_deployment' doesn't exist at /opt/otrs/Kernel/System/DB.pm line 694.

ERROR: OTRS-otrs.Daemon.pl - Daemon Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager-10 Perl: 5.16.3 OS: linux Time: Thu Aug 30 11:18:24 2018`

The webui opens but with 'root' and my password i set by adding `-e 'OTRS_ROOT_PASSWORD'='test'` i can't login. 'changeme' wont work either.

**Comment by juanluisbaptiste** [comment]
Is this still an issue ?

**Comment by juanluisbaptiste** [comment]
Excellent, closing the issue.
