### ISSUE TITLE
credentials-smtp.env is missing

### ISSUE THREAD

**Issue by rexcze** [juanluisbaptiste/docker-otrs#4]
Hello,

file credentials-smtp.env is missing thus howto for running docker-compose should be somehow changed. Would you be so kind to add some generic credentials-smtp.env or atleast provide info about how this file should be formated?

Thank you

**Comment by juanluisbaptiste** [comment]
You can see the contents of that file on the [SMTP relay](https://github.com/juanluisbaptiste/docker-postfix) container page.
