### ISSUE TITLE
how best restoring 5.x branch to docker and upgrade?

### ISSUE THREAD

**Issue by perler** [juanluisbaptiste/docker-otrs#40]
as the 5.x branch differs quite profoundly from the 6.x branch in regard to the docker-compose (and I have quite some trouble getting it running) I wonder, is it possible to use the 6.x branch docker-compose.yml replace the image with juanluisbaptiste/otrs:latest-5x and do the restore, than upgrade to 6.x according to the README?

**Comment by juanluisbaptiste** [comment]
I suppose, haven't tested it.
