### ISSUE TITLE
Setting OTRS_NUMBER_GENERATOR=AutoIncrement does not work

### ISSUE THREAD

**Issue by jmwebslave** [juanluisbaptiste/docker-otrs#41]
I seem to have a repeatable issue whereby setting AutoIncrement throws an error while the config file is being set up while the container boots.

otrs_1     | ERROR: OTRS-otrs.Daemon.pl - Daemon Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager-10 Perl: 5.16.3 OS: linux Time: Tue Sep 11 12:28:49 2018
otrs_1     |
otrs_1     |  Message: There was an error executing ConfigurationDeploySync: ERROR: OTRS-otrs.Daemon.pl - Daemon Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager-10 Perl: 5.16.3 OS: linux Time: Tue Sep 11 12:28:49 2018
otrs_1     |
otrs_1     |  Message: No deployments found in Database!
otrs_1     |
otrs_1     |  Traceback (64):
otrs_1     |    Module: Kernel::System::SysConfig::ConfigurationDeploySync Line: 3730
otrs_1     |    Module: (eval) Line: 129
otrs_1     |    Module: Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager::Run Line: 116
otrs_1     |    Module: (eval) Line: 316
otrs_1     |    Module: main::Start Line: 316
otrs_1     |    Module: /opt/otrs/bin/otrs.Daemon.pl Line: 137
otrs_1     |
otrs_1     |
otrs_1     |
otrs_1     |  Traceback (64):
otrs_1     |    Module: Kernel::System::Daemon::DaemonModules::BaseTaskWorker::_HandleError Line: 49
otrs_1     |    Module: Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager::Run Line: 134
otrs_1     |    Module: (eval) Line: 316
otrs_1     |    Module: main::Start Line: 316
otrs_1     |    Module: /opt/otrs/bin/otrs.Daemon.pl Line: 137
otrs_1     |

**Comment by juanluisbaptiste** [comment]
That error is always shown in a default install, it means that there is no configuration deployments waiting to be deployed. 

Did you try yo access the agent interface ?

**Comment by jmwebslave** [comment]
Sorry, it looks like I actually dropped the wrong paste.

This is correct:
`otrs_1     | [INFO] Starting a clean OTRS 6.0.10-01 Free installation ready to be configured !!
otrs_1     |
otrs_1     | [INFO] Found empty /opt/otrs/Kernel/, copying default configuration to it...
postfix_1  | /usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
postfix_1  |   'Supervisord is running as root and it is searching '
postfix_1  | 2018-09-12 05:10:24,812 CRIT Supervisor running as root (no user in config file)
postfix_1  | 2018-09-12 05:10:24,817 WARN Included extra file "/etc/supervisord.d/rsyslog.ini" during parsing
postfix_1  | 2018-09-12 05:10:24,818 WARN Included extra file "/etc/supervisord.d/readlog.ini" during parsing
postfix_1  | 2018-09-12 05:10:24,818 WARN Included extra file "/etc/supervisord.d/postfix.ini" during parsing
postfix_1  | 2018-09-12 05:10:24,907 INFO RPC interface 'supervisor' initialized
postfix_1  | 2018-09-12 05:10:24,908 CRIT Server 'unix_http_server' running without any HTTP authentication checking
postfix_1  | 2018-09-12 05:10:24,909 INFO supervisord started with pid 21
otrs_1     | [INFO] Done.
otrs_1     | [INFO] Copying default skins...
otrs_1     | [INFO] Done.
otrs_1     | [INFO] Updating configuration option DatabaseUser with value: otrs
otrs_1     | [INFO] Updating configuration option DatabasePw with value: [redacted]
otrs_1     | [INFO] Updating configuration option DatabaseHost with value: mariadb
otrs_1     | [INFO] Adding configuration option OTRSTimeZone with value: Australia/Melbourne
otrs_1     | [INFO] Adding configuration option UserDefaultTimeZone with value: Australia/Melbourne
otrs_1     | [INFO] Adding configuration option FQDN with value: [redacted]
otrs_1     | [INFO] Adding configuration option SendmailModule with value: Kernel::System::Email::SMTP
otrs_1     | [INFO] Adding configuration option SendmailModule::Host with value: postfix
otrs_1     | [INFO] Adding configuration option SendmailModule::Port with value: 25
otrs_1     | [INFO] Adding configuration option SecureMode with value: 1
otrs_1     | ERROR 1049 (42000) at line 1: Unknown database 'otrs'
otrs_1     | [INFO] Creating OTRS database...
otrs_1     | [INFO] Loading default db schemas...
otrs_1     | [INFO] Loading initial db inserts...
otrs_1     | [INFO] Loading initial schema constraints...
postfix_1  | 2018-09-12 05:10:25,911 INFO spawned: 'master' with pid 24
postfix_1  | 2018-09-12 05:10:25,914 INFO spawned: 'readlog' with pid 25
postfix_1  | 2018-09-12 05:10:25,923 INFO spawned: 'rsyslog' with pid 26
postfix_1  | 2018-09-12 05:10:26,464 INFO success: master entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
postfix_1  | 2018-09-12 05:10:26,465 INFO exited: master (exit status 0; expected)
otrs_1     | [INFO] Setting password for default admin account root@localhost to: [redacted]
otrs_1     | Successfully set password for user 'root@localhost'.
otrs_1     | [INFO] Reinstalling OTRS modules...
otrs_1     | [INFO] Done.
otrs_1     | ./functions.sh: line 225: Kernel::System::Ticket::Number::${{OTRS_NUMBER_GENERATOR}}: bad substitution
otrs_1     | [INFO] Starting supervisord...
otrs_1     | [INFO] Restarting OTRS daemon...
otrs_1     | /usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
otrs_1     |   'Supervisord is running as root and it is searching '
otrs_1     | 2018-09-12 05:10:27,331 CRIT Supervisor running as root (no user in config file)
otrs_1     | 2018-09-12 05:10:27,332 WARN Included extra file "/etc/supervisord.d/otrs.ini" during parsing
otrs_1     | 2018-09-12 05:10:27,375 INFO RPC interface 'supervisor' initialized
otrs_1     | 2018-09-12 05:10:27,377 CRIT Server 'unix_http_server' running without any HTTP authentication checking
otrs_1     | 2018-09-12 05:10:27,378 INFO supervisord started with pid 58
otrs_1     |
otrs_1     | Manage the OTRS daemon process.
otrs_1     |
otrs_1     | Daemon stopped
postfix_1  | 2018-09-12 05:10:27,466 INFO success: readlog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix_1  | 2018-09-12 05:10:27,466 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
otrs_1     | 2018-09-12 05:10:28,380 INFO spawned: 'httpd' with pid 64
otrs_1     | 2018-09-12 05:10:28,382 INFO spawned: 'crond' with pid 65
otrs_1     | 2018-09-12 05:10:28,384 INFO spawned: 'rsyslog' with pid 66
otrs_1     | 2018-09-12 05:10:29,439 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
otrs_1     | 2018-09-12 05:10:29,439 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
otrs_1     | 2018-09-12 05:10:29,439 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
otrs_1     |
otrs_1     | Manage the OTRS daemon process.
otrs_1     |
otrs_1     | Daemon started
otrs_1     | [INFO] OTRS Ready !
otrs_1     | ERROR: OTRS-otrs.Daemon.pl - Daemon Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager-10 Perl: 5.16.3 OS: linux Time: Wed Sep 12 05:10:29 2018
otrs_1     |
otrs_1     |  Message: There was an error executing ConfigurationDeploySync: ERROR: OTRS-otrs.Daemon.pl - Daemon Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager-10 Perl: 5.16.3 OS: linux Time: Wed Sep 12 05:10:29 2018
otrs_1     |
otrs_1     |  Message: No deployments found in Database!
otrs_1     |
otrs_1     |  Traceback (77):
otrs_1     |    Module: Kernel::System::SysConfig::ConfigurationDeploySync Line: 3730
otrs_1     |    Module: (eval) Line: 129
otrs_1     |    Module: Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager::Run Line: 116
otrs_1     |    Module: (eval) Line: 316
otrs_1     |    Module: main::Start Line: 316
otrs_1     |    Module: /opt/otrs/bin/otrs.Daemon.pl Line: 137
otrs_1     |
otrs_1     |
otrs_1     |
otrs_1     |  Traceback (77):
otrs_1     |    Module: Kernel::System::Daemon::DaemonModules::BaseTaskWorker::_HandleError Line: 49
otrs_1     |    Module: Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager::Run Line: 134
otrs_1     |    Module: (eval) Line: 316
otrs_1     |    Module: main::Start Line: 316
otrs_1     |    Module: /opt/otrs/bin/otrs.Daemon.pl Line: 137
otrs_1     |
`

So doing OTRS_NUMBER_GENERATOR=AutoIncrement in env actually causes this:
./functions.sh: line 225: Kernel::System::Ticket::Number::${{OTRS_NUMBER_GENERATOR}}: bad substitution

And as a result later the daemon will not run.

**Comment by juanluisbaptiste** [comment]
I can reproduce it, working on a fix.

**Comment by juanluisbaptiste** [comment]
Fixed.
