### ISSUE TITLE
How to restore

### ISSUE THREAD

**Issue by houstek** [juanluisbaptiste/docker-otrs#46]
Hi,
I made a backup of my legacy OTRS install (v5.0.27) with : 
linux:/opt/otrs/scripts# ./backup.pl -d /backup/
I put the backup in the folder ./volumes/backup 
When trying to restore it, I run into the following error:

> 
```
mysqladmin:

 connect to server at 'mariadb' failed

error: 'Lost connection to MySQL server at 'reading initial communication packet', system error: 111'

[INFO] Database server is not available. Waiting 2 seconds...

[INFO] Database server is up !

[INFO] Restoring OTRS backup: "2018-11-08_09-34" for host 

[INFO] Updating database password on configuration file...

sed: can't read /opt/otrs/Kernel/Config.pm: No such file or directory

[INFO] Updating databse server on configuration file...

sed: can't read /opt/otrs/Kernel/Config.pm: No such file or directory

[INFO] Updating SMTP server on configuration file...

grep: /opt/otrs/Kernel/Config.pm: No such file or directory

[INFO] Adding configuration option SendmailModule with value: Kernel::System::Email::SMTP

sed: can't read /opt/otrs/Kernel/Config.pm: No such file or directory

grep: /opt/otrs/Kernel/Config.pm: No such file or directory

[INFO] Adding configuration option SendmailModule::Host with value: postfix

sed: can't read /opt/otrs/Kernel/Config.pm: No such file or directory

grep: /opt/otrs/Kernel/Config.pm: No such file or directory

[INFO] Adding configuration option SendmailModule::Port with value: 25

sed: can't read /opt/otrs/Kernel/Config.pm: No such file or directory

ERROR 1049 (42000) at line 1: Unknown database 'otrs'

[INFO] Creating OTRS database...

sed: can't read /opt/otrs/Kernel/Config.pm: No such file or directory

tar (child): /var/otrs/backups/"2018-11-08_09-34": Cannot open: No such file or directory

tar (child): Error is not recoverable: exiting now

tar: Child returned status 2

tar: Error is not recoverable: exiting now

[ERROR] Couldn't uncompress main backup file !!
```
> 

My compose : 
```
version: '3'

services:
  otrs:
    image: juanluisbaptiste/otrs:5.0.27
    build: otrs
    ports:
      - '80:80'
    depends_on:
      - mariadb
    env_file: otrs-setup.env
    volumes:
      - ./volumes/config:/opt/otrs/Kernel
      - ./volumes/skins:/opt/otrs/var/httpd/htdocs/skins/
      - ./volumes/backup:/var/otrs/backups
      - /etc/localtime:/etc/localtime:ro
  mariadb:
    image: juanluisbaptiste/otrs-mariadb:latest
    build: mariadb
    expose:
      - "3306"
    env_file: otrs-setup.env
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

```

**Comment by houstek** [comment]
my otrs-setup.env

> #####################################
# Database Configuration
#####################################

# Name of database to use. Default is otrs.
#OTRS_DB_NAME=otrs

# Hostname or IP address of the database server. Default is mariadb.
#OTRS_DB_HOST=mariadb

# Port of the database server. Default is 3306.
#OTRS_DB_PORT=3306

# Database user. Default is otrs.
#OTRS_DB_USER=otrs

# otrs user database password. Default password is changeme
OTRS_DB_PASSWORD=xxxxx

# Database root password so it can be setup. Default password is changeme.
MYSQL_ROOT_PASSWORD=xxxxx

#####################################
# OTRS Configuration
#####################################

# Container startup mode, possible values:
#   - no      : Starts OTRS ready to be configured.
#   - yes     : Runs the OTRS installer.
#   - restore : Restores the backup specified by OTRS_BACKUP_DATE environment variable. Please check the README file for details.
OTRS_INSTALL=restore
OTRS_BACKUP_DATE=2018-11-08_09-34
OTRS_DEBUG=no

# On backup restore it drops the otrs database it if already exists (by default the container will fail if the database already exists).
OTRS_DROP_DATABASE=yes

# root@localhost user password. Default password is changeme
OTRS_ROOT_PASSWORD=xxxxx

# Sets the container's hostname (auto-generated if not defined).
#OTRS_HOSTNAME=

# Set the default language for both agent and customer interfaces (For example, "es" for spanish).
OTRS_LANGUAGE=fr

# Sets the default timezone.
#OTRS_TIMEZONE=UTC

# Sets the starting point for the ticket counter.
#OTRS_TICKET_COUNTER=

# Sets the ticket number generator, possible values are : DateChecksum, Date, AutoIncrement or Random.
#OTRS_NUMBER_GENERATOR=DateChecksum

# To disable the OTRS ASCII logo at container startup.
#SHOW_OTRS_LOGO=yes

#####################################
#           EXPERIMENTAL !!
#       Test at your own risk
#####################################
########## Version Upgrade ##########

# Do a MAJOR version upgrade. Possible values: yes, no (default). Please check the README file for details.
#OTRS_UPGRADE=no

#####################################
# SMTP Relay Configuration
#####################################

# Server address of the SMTP server to use.
#SMTP_SERVER=smtp.domaine.local

# Port address of the SMTP server to use. (Optional, Default value: 587)
SMTP_PORT=25

# Username to authenticate with.
#SMTP_USERNAME=

# Password of the SMTP user.
#SMTP_PASSWORD=

# Server hostname for the Postfix container. Emails will appear to come from the hostname's domain.
#SERVER_HOSTNAME=

**Comment by houstek** [comment]
my otrs-setup.env

> 

> 

> 

`
#####################################
# Database Configuration
#####################################

# Name of database to use. Default is otrs.
#OTRS_DB_NAME=otrs

# Hostname or IP address of the database server. Default is mariadb.
#OTRS_DB_HOST=mariadb

# Port of the database server. Default is 3306.
#OTRS_DB_PORT=3306

# Database user. Default is otrs.
#OTRS_DB_USER=otrs

# otrs user database password. Default password is changeme
OTRS_DB_PASSWORD=qdJ3pEP0Toy8RoR5

# Database root password so it can be setup. Default password is changeme.
MYSQL_ROOT_PASSWORD=M1tr0luxmysql

#####################################
# OTRS Configuration
#####################################

# Container startup mode, possible values:
#   - no      : Starts OTRS ready to be configured.
#   - yes     : Runs the OTRS installer.
#   - restore : Restores the backup specified by OTRS_BACKUP_DATE environment variable. Please check the README file for details.
OTRS_INSTALL=restore
OTRS_BACKUP_DATE=2018-11-08_09-34
OTRS_DEBUG=no

# On backup restore it drops the otrs database it if already exists (by default the container will fail if the database already exists).
OTRS_DROP_DATABASE=yes

# root@localhost user password. Default password is changeme
OTRS_ROOT_PASSWORD=123456

# Sets the container's hostname (auto-generated if not defined).
#OTRS_HOSTNAME=

# Set the default language for both agent and customer interfaces (For example, "es" for spanish).
OTRS_LANGUAGE=fr

# Sets the default timezone.
#OTRS_TIMEZONE=UTC

# Sets the starting point for the ticket counter.
#OTRS_TICKET_COUNTER=

# Sets the ticket number generator, possible values are : DateChecksum, Date, AutoIncrement or Random.
#OTRS_NUMBER_GENERATOR=DateChecksum

# To disable the OTRS ASCII logo at container startup.
#SHOW_OTRS_LOGO=yes

#####################################
#           EXPERIMENTAL !!
#       Test at your own risk
#####################################
########## Version Upgrade ##########

# Do a MAJOR version upgrade. Possible values: yes, no (default). Please check the README file for details.
#OTRS_UPGRADE=no

#####################################
# SMTP Relay Configuration
#####################################

# Server address of the SMTP server to use.
#SMTP_SERVER=smtp.servyr.local

# Port address of the SMTP server to use. (Optional, Default value: 587)
SMTP_PORT=25

# Username to authenticate with.
#SMTP_USERNAME=

# Password of the SMTP user.
#SMTP_PASSWORD=

# Server hostname for the Postfix container. Emails will appear to come from the hostname's domain.
#SERVER_HOSTNAME=

`

**Comment by houstek** [comment]
he seems not to find the backup folder. Yet he is present.
![2018-11-09_15h03_54](https://user-images.githubusercontent.com/16977281/48266847-f08aee00-e430-11e8-8f39-d81995b22adf.png)
![2018-11-09_15h05_05](https://user-images.githubusercontent.com/16977281/48266858-f7b1fc00-e430-11e8-950c-4ca38a012ddc.png)

**Comment by juanluisbaptiste** [comment]
Hi,

Please try latest build (latest-5x tag).

**Comment by houstek** [comment]
Same problem
With OTRS_INSTALL=no , everything is OK

`
...
mariadb_1  | Finished mysql_install_db
otrs_1     | mysqladmin: connect to server at 'mariadb' failed
otrs_1     | error: 'Lost connection to MySQL server at 'reading initial communication packet', system error: 111'
otrs_1     | [INFO] Database server is not available. Waiting 2 seconds...
mariadb_1  | 181110 08:38:08 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
mariadb_1  | 181110 08:38:08 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
otrs_1     | [INFO] Database server is up !
otrs_1     | [INFO] Restoring OTRS backup: 2018-11-08_09-35 for host
otrs_1     | [INFO] Updating database password on configuration file...
otrs_1     | sed: can't read /opt/otrs/Kernel/Config.pm: No such file or directory
otrs_1     | [INFO] Updating databse server on configuration file...
otrs_1     | sed: can't read /opt/otrs/Kernel/Config.pm: No such file or directory
otrs_1     | [INFO] Updating SMTP server on configuration file...
otrs_1     | grep: /opt/otrs/Kernel/Config.pm: No such file or directory
otrs_1     | [INFO] Adding configuration option SendmailModule with value: Kernel::System::Email::SMTP
otrs_1     | sed: can't read /opt/otrs/Kernel/Config.pm: No such file or directory
otrs_1     | grep: /opt/otrs/Kernel/Config.pm: No such file or directory
otrs_1     | [INFO] Adding configuration option SendmailModule::Host with value: postfix
otrs_1     | sed: can't read /opt/otrs/Kernel/Config.pm: No such file or directory
otrs_1     | grep: /opt/otrs/Kernel/Config.pm: No such file or directory
otrs_1     | [INFO] Adding configuration option SendmailModule::Port with value: 25
otrs_1     | sed: can't read /opt/otrs/Kernel/Config.pm: No such file or directory
otrs_1     | ERROR 1049 (42000) at line 1: Unknown database 'otrs'
otrs_1     | [INFO] Creating OTRS database...
otrs_1     | sed: can't read /opt/otrs/Kernel/Config.pm: No such file or directory
otrs_1     | Can't locate Encode/Locale.pm in @INC (@INC contains: /opt/otrs/Custom /opt/otrs/Kernel/cpan-lib /opt/otrs /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at Kernel/System/Encode.pm line 15.
otrs_1     | BEGIN failed--compilation aborted at Kernel/System/Encode.pm line 15.
otrs_1     | Compilation failed in require at Kernel/System/ObjectManager.pm line 30.
otrs_1     | BEGIN failed--compilation aborted at Kernel/System/ObjectManager.pm line 30.
otrs_1     | Compilation failed in require at /opt/otrs/scripts/restore.pl line 30.
otrs_1     | BEGIN failed--compilation aborted at /opt/otrs/scripts/restore.pl line 30.
otrs_1     | [ERROR] Couldn't load OTRS backup !!
docker-otrs_otrs_1 exited with code 1

`

**Comment by juanluisbaptiste** [comment]
That's not the same issue as shown in the screenshot which is that the backup file isn't being found. This same error you post it at first, then you modified something and send the screenshot that is of a functional install (with the restore bug). 

What's the image hash ?

**Comment by houstek** [comment]
ok, let's go back to zero
I made a backup of my legacy OTRS install (v5.0.27) with :
#/opt/otrs/scripts# ./backup.pl -d /backup/
I put the backup in the folder ./volumes/backup

docker compose: https://pastebin.com/BYAF0e54
otrs-setup.env: https://pastebin.com/dfuYMVA3
image hash: `juanluisbaptiste/otrs           latest-5x           sha256:a81ffb4159122c617b1242f766d0157091caf954b4df8b6710caf043cd29f56d`
with OTRS_INSTALL = no, I have no errors, OTRS launches and the backup directory is accessible from the container :

![2018-11-11_07h38_21](https://user-images.githubusercontent.com/16977281/48309985-b97a2100-e585-11e8-87d9-47b8d79d010c.png)
![2018-11-11_07h39_04](https://user-images.githubusercontent.com/16977281/48309984-b97a2100-e585-11e8-8d31-e60f4f259102.png)

Now, I'm doing a docker-compose stop, and change OTRS_INSTALL = restore

![2018-11-11_07h43_25](https://user-images.githubusercontent.com/16977281/48310000-1ece1200-e586-11e8-8545-e8e1bc5514ac.png)

**Comment by houstek** [comment]
Restoring the backup in manual mode works well:

![2018-11-12_09h18_10](https://user-images.githubusercontent.com/16977281/48334776-13e5b100-e65c-11e8-9838-3c4d284d0bce.png)

**Comment by juanluisbaptiste** [comment]
Were you able to restore the backup ? I can restore without issues. I started a clean OTRS 5 install, created a backup, then stopped the container and set:

```
OTRS_INSTALL=restore
OTRS_BACKUP_DATE=2018-12-13_15-56
OTRS_DROP_DATABASE=yes

```

To restore it, this is the output:

```
docker-otrs-5x $ docker-compose up
WARNING: Dependency conflict: an older version of the 'docker-py' package may be polluting the namespace. If you're experiencing crashes, run the following command to remedy the issue:
pip uninstall docker-py; pip uninstall docker; pip install docker
Starting dockerotrs5x_mariadb_1 ... done
Recreating dockerotrs5x_otrs_1 ... done
Attaching to dockerotrs5x_mariadb_1, dockerotrs5x_otrs_1
mariadb_1  | 181213 16:29:43 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
otrs_1     | mysqladmin: connect to server at 'mariadb' failed
otrs_1     | error: 'Lost connection to MySQL server at 'reading initial communication packet', system error: 111'
mariadb_1  | 181213 16:29:43 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
otrs_1     | [INFO] Database server is not available. Waiting 2 seconds...
otrs_1     | [INFO] Database server is up !
otrs_1     | [INFO] Restoring OTRS backup: 2018-12-13_15-56 for host support.cachesimple.com
otrs_1     | [INFO] Updating database password on configuration file...
otrs_1     | [INFO] Updating databse server on configuration file...
otrs_1     | [INFO] Updating SMTP server on configuration file...
otrs_1     | [INFO] Updating configuration option SendmailModule with value: Kernel::System::Email::SMTP
otrs_1     | [INFO] Updating configuration option SendmailModule::Host with value: postfix
otrs_1     | [INFO] Updating configuration option SendmailModule::Port with value: 25
otrs_1     | [INFO] OTRS_DROP_DATABASE=yes, Dropping existing database
otrs_1     | 
otrs_1     | [INFO] Creating OTRS database...
otrs_1     | Restore /var/otrs/backups/2018-12-13_15-56//Config.tar.gz ...
otrs_1     | Restore /var/otrs/backups/2018-12-13_15-56//Application.tar.gz ...
otrs_1     | create MySQL
otrs_1     | decompresses SQL-file ...
otrs_1     | cat SQL-file into MySQL database
otrs_1     | compress SQL-file...
otrs_1     | [WARNING] OTRS version of backup being restored: 5.0.30
otrs_1     | [WARNING] OTRS version of this container: 5.0.32
otrs_1     | [WARNING] Backup version older than current OTRS version, fixing...
otrs_1     | [INFO] Done.
otrs_1     | [INFO] Updating default skin for users in backup...
otrs_1     | [INFO] Reinstalling OTRS modules...
otrs_1     | [INFO] Done.
otrs_1     | Setting permissions on /opt/otrs
otrs_1     | /
otrs_1     | Cron.sh - start/stop OTRS cronjobs
otrs_1     | Copyright (C) 2001-2018 OTRS AG, https://otrs.com/
otrs_1     | (using /opt/otrs) done
otrs_1     | otrs.Daemon.pl - the OTRS daemon
otrs_1     | Copyright (C) 2001-2018 OTRS AG, https://otrs.com/
otrs_1     | 
otrs_1     | Daemon started
otrs_1     | Processing ticket escalation events ...
otrs_1     | Done.
otrs_1     | Checking availability of OTRS Business Solution™...
otrs_1     | No need to execute the availability check at this moment, skipping...
otrs_1     | Done.
otrs_1     | Checking the OTRS Business Solution™ entitlement status...
otrs_1     | OTRS Business Solution™ is not installed in this system, skipping...
otrs_1     | Done.
otrs_1     | 
otrs_1     | No configured mail accounts found!
otrs_1     | 
otrs_1     | Collecting asynchronous support data...
otrs_1     | Done.
otrs_1     | Generating dashboard widgets statistics...
otrs_1     | Done.
otrs_1     | Rebuilding the system configuration...
otrs_1     | Done.
otrs_1     | Deleting cache...
otrs_1     | Done.
otrs_1     | [INFO] Starting supervisord...
otrs_1     | [INFO] Restarting OTRS daemon...
otrs_1     | 2018-12-13 16:29:54,474 CRIT Supervisor running as root (no user in config file)
otrs_1     | 2018-12-13 16:29:54,481 INFO /var/tmp/supervisor.sock:Medusa (V1.1.1.1) started at Thu Dec 13 16:29:54 2018
otrs_1     |    Hostname: <unix domain socket>
otrs_1     |    Port:/var/tmp/supervisor.sock
otrs_1     | 2018-12-13 16:29:54,513 CRIT Running without any HTTP authentication checking
otrs_1     | 2018-12-13 16:29:54,514 INFO supervisord started with pid 87
otrs_1     | 2018-12-13 16:29:54,515 INFO spawned: 'httpd' with pid 90
otrs_1     | 2018-12-13 16:29:54,516 INFO spawned: 'crond' with pid 91
otrs_1     | 2018-12-13 16:29:54,520 INFO spawned: 'rsyslog' with pid 92
otrs_1     | otrs.Daemon.pl - the OTRS daemon
otrs_1     | Copyright (C) 2001-2018 OTRS AG, https://otrs.com/
otrs_1     | 
otrs_1     | Daemon stopped
otrs_1     | 2018-12-13 16:29:55,557 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
otrs_1     | 2018-12-13 16:29:55,557 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
otrs_1     | 2018-12-13 16:29:55,558 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
otrs_1     | otrs.Daemon.pl - the OTRS daemon
otrs_1     | Copyright (C) 2001-2018 OTRS AG, https://otrs.com/
otrs_1     | 
otrs_1     | Daemon started
otrs_1     | [INFO] OTRS Ready !

```

I can only tell you to make sure you have the latest image (sudo docker pull juanluisbaptiste/otrs:latest-5x) and set OTRS_DEBUG=yes and see if there's more info that can help you debug the problem.

**Comment by juanluisbaptiste** [comment]
No answer so closing as fixed.
