### ISSUE TITLE
Port Number

### ISSUE THREAD

**Issue by peterheather88** [juanluisbaptiste/docker-otrs#49]
I am setting the parameter OTRS_DB_PORT = 50033

With debug set I am getting 

++ mysqladmin ping -h xxx.xxx.xxx.xxx -P 3306 -u root --password=xxxxxxxxx  --silent --connect_timeout=3
+ '[' '!' '' ']'
+ print_info 'Database server is not available. Waiting 2 seconds...'
+ echo -e '\e[46m[INFO]\e[0m Database server is not available. Waiting 2 seconds...'
+ sleep 2

Note: I have blanked out the IP address and password 

Form the above looks like the OTRS_DB_PORT parameter is not changing the default port number which is remaining as 3306.

What I doing worng?

Thanks,  Pete

**Comment by juanluisbaptiste** [comment]
Yoú must have something wrong with your setup, if you look at the code OTRS_DB_PORT is correctly set:

```bash
mysqlcmd="mysql -uroot -h ${OTRS_DB_HOST} -P ${OTRS_DB_PORT} -p${MYSQL_ROOT_PASSWORD}
```

**Comment by juanluisbaptiste** [comment]
Please pull and try again, the custom port value was getting lost before that line.

**Comment by juanluisbaptiste** [comment]
This is the [commit](https://github.com/juanluisbaptiste/docker-otrs/commit/36b667eedb9586f75bb8b8ecda32cda681621af1), the fix was mistakenly added with another commit.

**Comment by juanluisbaptiste** [comment]
Were you able to test ?

**Comment by peterheather88** [comment]
Hello

 

I am in China …. It harder to test here

 

I will try again over the weekend

 

Pete

**Comment by juanluisbaptiste** [comment]
No answer so closing as fixed.
