### ISSUE TITLE
Configure gmail

### ISSUE THREAD

**Issue by nabidul** [juanluisbaptiste/docker-otrs#53]
Good morning!

I really appreciate if some one could help me, I'm getting crazy trying to configure a Gmail account as my main account, but I really don't know if it is posible, I try to configure it by IMAPS(imap.gmail.com & INBOX folder) and it doesn't work. 
In addition, I have checked all the security settings in GMail and IMAP is available. And also, ping imap.gmail.com and telnet imap.gmail.com 993 from container was succesufull. 

Would anybody please kindly help me to solve the problem?

**Comment by juanluisbaptiste** [comment]
This is not a support forum and your question has nothing to do with this container, go to OTRS forums.

**Comment by nabidul** [comment]
I am using your image(juanluisbaptiste/otrs:latest) to install Otrs. This is why I was asking here. I am so sorry if its not the righht place, I thought maybe it would have to do with the installation.

**Comment by juanluisbaptiste** [comment]
If the container starts up, you can login and don't have any issues with the stuff you configured on the .env file then the problem probably is in OTRS. 

This image is just a _container_ for OTRS, it does not modify it in any way, only sets up a database, a smtp relay and setups the installation according to what the installer can configure so you don't need to run it, as the README file says.
