### ISSUE TITLE
Unable to send emails from newly build images

### ISSUE THREAD

**Issue by alexawka** [juanluisbaptiste/docker-otrs#54]
Hi.
I am using your project source files to build image with some minor tweaks. Everything was great until recent, when I tried to upgrade to 6.14 - outgoing emails stopped sending with "SMTP authentication failed (SMTP code: 500, ErrorMessage: 500, Command unknown: 'AUTH')."
The only change is OTRS version in Dockerfile
Rolled back to 6.12 image and e-mails started working just fine.
Now for the testing:
1. Fired up different environment
2. Checked out commit that was used for 6.12 image build
3. Build 6.12 image
4. Tested outgoing e-mails - not working
5. Imported "old" 6.12 image - e-mails are working.
I have noticed, that images build from same source have different size:
Build month ago:
![image](https://user-images.githubusercontent.com/11499445/50098692-17ed8b80-0225-11e9-8f7f-b0b93c112040.png)
Built today:
![image](https://user-images.githubusercontent.com/11499445/50098750-39e70e00-0225-11e9-8e89-34bfd769c2e3.png)
It seems that difference in size comes in this step 9:
"RUN yum install -y yum-plugin-fastestmirror && yum install -y epel-release && yum update -y && yum -y install cronie httpd mysql mod_perl perl-core "perl(Crypt::SSLeay)" "perl(Net::LDAP)" "perl(URI)" procmail "perl(Date::Format)" "perl(LWP::UserAgent)" "perl(Net::DNS)" "perl(IO::Socket::SSL)" "perl(XML::Parser)" "perl(Apache2::Reload)" "perl(Crypt::Eksblowfish::Bcrypt)" "perl(Encode::HanExtra)" "perl(GD)" "perl(GD::Text)" "perl(GD::Graph)" "perl(JSON::XS)" "perl(Mail::IMAPClient)" "perl(PDF::API2)" "perl(DateTime)" "perl(Text::CSV_XS)" "perl(YAML::XS)" "perl(Text::CSV_XS)" "perl(DBD::mysql)" rsyslog supervisor tar which && yum install -y http://ftp.otrs.org/pub/otrs/RPMS/rhel/7/otrs-${OTRS_VERSION}.noarch.rpm && /opt/otrs/bin/otrs.CheckModules.pl && yum clean all"

Could you please confirm if the issue is reproducible

P.S. - I am using SMTPTLS and Office365 account

**Comment by juanluisbaptiste** [comment]
Email handling is handled outside the OTRS container as the README file says. If what you mean is that you have changed this container configuration to use another SMTP server instead of the SMTP container we use then this has nothing to do with the container and you should check OTRS forums or bvug reports.

In any case this has nothitng to do with this container, closing.
