### ISSUE TITLE
Postfix without authentication

### ISSUE THREAD

**Issue by perler** [juanluisbaptiste/docker-otrs#56]
The postfix container exepcts SMTP_PASSWORD and SMTP_USERNAME as parameters. But our smarthost doesn't use authentication. 

Can we make this optionally?

**Comment by juanluisbaptiste** [comment]
PR welcome, implementation should respect current behavior as the default.

**Comment by juanluisbaptiste** [comment]
Closing it, reading it again I see that this is not an issue with this project but with [docker-postfix](https://github.com/juanluisbaptiste/docker-postfix).
