### ISSUE TITLE
OTRS_TIMEZONE values

### ISSUE THREAD

**Issue by barajas-victor** [juanluisbaptiste/docker-otrs#58]
Hi i wold like to know what are the **OTRS_TIMEZONE** values. The only value i can see is **UTC**, but i like to setup to **Mexico_City**, how do i do that. I tried UTC-6 but it did not work. I really apreciate your help.

**Comment by juanluisbaptiste** [comment]
You use the values of the [tz database] (https://en.m.wikipedia.org).

**Comment by juanluisbaptiste** [comment]
Any other question ?

**Comment by barajas-victor** [comment]
No, thats all, thank you.
