### ISSUE TITLE
User otrs/root is operating with the wrong locale

### ISSUE THREAD

**Issue by ftvadmin** [juanluisbaptiste/docker-otrs#59]
**Reporting a bug**
> First of all, this is **not** a problem reporting forum, only report if you are pretty sure what you are experiencing is a bug with this image _and_ docker, not a configuration issue of OTRS, for that you can go to the [OTRS community forums](https://forums.otterhub.org/). 
> 
> If the container starts up, you can login and don't have any issues with the stuff you configured on the .env file, then the problem probably is in OTRS.

Probably, but the locale of the user `root`/`otrs` could be changed during image-creation.

> Also be sure you are using the latest image by doing _docker pull juanluisbaptiste/otrs_.

> Please post the image version you are using (latest, 6.0.x, latest-5x, etc).

I'm on 6.0.17

```
[otrs@16499fa9a4af ~]$ /opt/otrs/bin/otrs.Console.pl Admin::User::SetPassword root@localhost
Error: The terminal encoding should be set to 'utf-8', but is 'ansi_x3.4-1968'. Some characters might not be displayed correctly.
```
```
[otrs@16499fa9a4af ~]$ locale charmap
ANSI_X3.4-1968
```

As the otrs - user is operating with wrong locale - settings the initial setup of the root@localhost-password can fail. Furthermore other operations could result in unexpected behaviour.

**Expected behavior**
User root/otrs uses utf-8.

**Comment by ftvadmin** [comment]
Sorry seems I messed things up. But nevertheless the error I've mentioned seems to be the cause why passwords with special characters will be messed up so you can't login until you change the password by hand.
I even don't know if this will have effect on other things.

**Comment by ftvadmin** [comment]
Seems like this is just a symptom so I'll close the issue for now.

**Comment by juanluisbaptiste** [comment]
I added LANG=en_US.UTF-8 and LANGUAGE=en_US.UTF-8 to the Dockerfile in any case.

Thanks for spotting this.
