### ISSUE TITLE
Docker-otrs on aws ec2 instance

### ISSUE THREAD

**Issue by vijaykhurana** [juanluisbaptiste/docker-otrs#6]
Running otrs container on ec2 instance remotely results in the following error. Though ssh into ec2 instance and then running the container works fine. 

sudo  docker-compose -f docker-compose-prod.yml  up
Starting sgcotrs_postfix_1
Starting sgcotrs_data_1
Starting sgcotrs_data-otrs_1
Starting sgcotrs_mariadb_1
Starting sgcotrs_otrs_1
Attaching to sgcotrs_data-otrs_1, sgcotrs_data_1, sgcotrs_postfix_1, sgcotrs_mariadb_1, sgcotrs_otrs_1
postfix_1    | postmap: fatal: bad string length 0 < 1: myhostname = 
postfix_1    | /usr/lib/python2.7/site-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
postfix_1    |   'Supervisord is running as root and it is searching '
mariadb_1    | 161224 08:00:57 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
otrs_1       | [INFO] Enter
mariadb_1    | 161224 08:00:57 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
postfix_1    | 2016-12-24 08:00:53,561 CRIT Supervisor running as root (no user in config file)
otrs_1       | [INFO] Server is up !
postfix_1    | 2016-12-24 08:00:53,561 WARN Included extra file "/etc/supervisord.d/postfix.ini" during parsing
postfix_1    | Unlinking stale socket /var/tmp/supervisor.sock
otrs_1       | [INFO] Starting  OTRS 5.0.15-01 installer !!
mariadb_1    | 161224 08:01:01 mysqld_safe mysqld from pid file /var/run/mariadb/mariadb.pid ended
otrs_1       | [INFO] Starting supervisord...
postfix_1    | 2016-12-24 08:00:53,898 INFO RPC interface 'supervisor' initialized
otrs_1       | [INFO] Restarting OTRS daemon...
otrs_1       | 2016-12-24 08:01:01,846 CRIT Supervisor running as root (no user in config file)
postfix_1    | 2016-12-24 08:00:53,898 CRIT Server 'unix_http_server' running without any HTTP authentication checking
otrs_1       | Unlinking stale socket /var/tmp/supervisor.sock
postfix_1    | 2016-12-24 08:00:53,899 INFO supervisord started with pid 11
otrs_1       | 2016-12-24 08:01:02,338 INFO /var/tmp/supervisor.sock:Medusa (V1.1.1.1) started at Sat Dec 24 08:01:02 2016
otrs_1       | 	Hostname: <unix domain socket>
postfix_1    | 2016-12-24 08:00:54,903 INFO spawned: 'master' with pid 14
otrs_1       | 	Port:/var/tmp/supervisor.sock
postfix_1    | 2016-12-24 08:00:55,906 INFO success: master entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
postfix_1    | 2016-12-24 08:00:55,916 INFO exited: master (exit status 1; not expected)
otrs_1       | 2016-12-24 08:01:02,382 CRIT Running without any HTTP authentication checking
otrs_1       | 2016-12-24 08:01:02,383 INFO supervisord started with pid 10
otrs_1       | 2016-12-24 08:01:02,385 INFO spawned: 'httpd' with pid 13
otrs_1       | 2016-12-24 08:01:02,389 INFO spawned: 'crond' with pid 14
otrs_1       | 2016-12-24 08:01:02,392 INFO spawned: 'rsyslog' with pid 15
otrs_1       | 2016-12-24 08:01:02,412 INFO exited: rsyslog (exit status 1; not expected)
otrs_1       | 2016-12-24 08:01:02,413 INFO received SIGCLD indicating a child quit
sgcotrs_data-otrs_1 exited with code 0
sgcotrs_data_1 exited with code 0
otrs_1       | 2016-12-24 08:01:03,430 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
otrs_1       | 2016-12-24 08:01:03,430 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
otrs_1       | 2016-12-24 08:01:03,433 INFO spawned: 'rsyslog' with pid 16
otrs_1       | 2016-12-24 08:01:03,443 INFO exited: rsyslog (exit status 1; not expected)
otrs_1       | 2016-12-24 08:01:03,444 INFO received SIGCLD indicating a child quit
otrs_1       | otrs.Daemon.pl - the OTRS daemon
otrs_1       | Copyright (C) 2001-2016 OTRS AG, http://otrs.com/
otrs_1       | 
otrs_1       | Daemon stopped
sgcotrs_mariadb_1 exited with code 0
otrs_1       | 2016-12-24 08:01:05,450 INFO spawned: 'rsyslog' with pid 26
otrs_1       | 2016-12-24 08:01:05,460 INFO exited: rsyslog (exit status 1; not expected)
otrs_1       | 2016-12-24 08:01:05,460 INFO received SIGCLD indicating a child quit
otrs_1       | otrs.Daemon.pl - the OTRS daemon
otrs_1       | Copyright (C) 2001-2016 OTRS AG, http://otrs.com/
otrs_1       | 
otrs_1       | **ERROR: OTRS-otrs.Daemon.pl-98 Perl: 5.10.1 OS: linux Time: Sat Dec 24 08:01:07 2016
otrs_1       | 
otrs_1       |  Message: Don't have write permissions in directory '/opt/otrs/var/run/': 
otrs_1       |** 
otrs_1       |  Traceback (29): 
otrs_1       |    Module: main::_PIDLock Line: 483
otrs_1       |    Module: main::Start Line: 191
otrs_1       |    Module: /opt/otrs/bin/otrs.Daemon.pl Line: 138

**Comment by juanluisbaptiste** [comment]
Please attach your docker-compose.yml file.

**Comment by vijaykhurana** [comment]
Its the default docker-compose-prod.yml with OTRS_INSTALL: "yes" uncommented. 

version: '2'
services:
  otrs:
    image: juanluisbaptiste/otrs:latest
    ports:
    - "80:80"
    links:
    - mariadb:mariadb
    - postfix:postfix
    volumes_from:
    - data-otrs
    environment:
         OTRS_INSTALL: "yes"
  mariadb:
    image: juanluisbaptiste/otrs-mariadb:latest
    expose:
    - "3306"
    volumes_from:
    - data
    environment:
        MYSQL_ROOT_PASSWORD: changeme
  postfix:
     image: juanluisbaptiste/postfix:latest
     expose:
     - "25"
     env_file: credentials-smtp.env
  data:
    image: centos/mariadb:latest
    volumes:
    - ./volumes/mysql:/var/lib/mysql
    - "/etc/localtime:/etc/localtime:ro"
    command: /bin/true
  data-otrs:
    image: juanluisbaptiste/otrs:latest
    volumes:
    - ./volumes/config:/opt/otrs/Kernel
    - "./otrs/backup:/var/otrs/backups"
    - "/etc/localtime:/etc/localtime:ro"
    command: /bin/true

**Comment by juanluisbaptiste** [comment]
You have to make sure the _otrs_ directory of the data volume has write permissions on the host where its mapped to.

**Comment by juanluisbaptiste** [comment]
I updated the README.md file to be more clear on this.

**Comment by vijaykhurana** [comment]
Please see the following output :

sudo /usr/local/bin/docker-compose up
Starting dockerotrs_postfix_1
Starting dockerotrs_data_1
Starting dockerotrs_data-otrs_1
Starting dockerotrs_mariadb_1
Recreating dockerotrs_otrs_1
Attaching to dockerotrs_data-otrs_1, dockerotrs_postfix_1, dockerotrs_data_1, dockerotrs_mariadb_1, dockerotrs_otrs_1
postfix_1    | postmap: fatal: bad string length 0 < 1: myhostname = 
dockerotrs_data-otrs_1 exited with code 0
dockerotrs_data_1 exited with code 0
mariadb_1    | 170103 04:22:12 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
mariadb_1    | 170103 04:22:12 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
otrs_1       | [INFO] Enter
otrs_1       | [INFO] Server is up !
otrs_1       | [INFO] Starting  OTRS 5.0.15-01 installer !!
otrs_1       | [INFO] Starting supervisord...
otrs_1       | [INFO] Restarting OTRS daemon...
otrs_1       | 2017-01-03 04:22:14,125 CRIT Supervisor running as root (no user in config file)
otrs_1       | 2017-01-03 04:22:14,172 INFO /var/tmp/supervisor.sock:Medusa (V1.1.1.1) started at Tue Jan  3 04:22:14 2017
otrs_1       | 	Hostname: <unix domain socket>
otrs_1       | 	Port:/var/tmp/supervisor.sock
otrs_1       | Can't locate Encode/Locale.pm in @INC (@INC contains: /opt/otrs/Custom /opt/otrs/Kernel/cpan-lib /opt/otrs /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at Kernel/System/Encode.pm line 15.
otrs_1       | BEGIN failed--compilation aborted at Kernel/System/Encode.pm line 15.
otrs_1       | Compilation failed in require at Kernel/System/ObjectManager.pm line 29.
otrs_1       | BEGIN failed--compilation aborted at Kernel/System/ObjectManager.pm line 29.
otrs_1       | Compilation failed in require at /opt/otrs/bin/otrs.Daemon.pl line 35.
otrs_1       | BEGIN failed--compilation aborted at /opt/otrs/bin/otrs.Daemon.pl line 35.
otrs_1       | 2017-01-03 04:22:14,293 CRIT Running without any HTTP authentication checking
otrs_1       | 2017-01-03 04:22:14,294 INFO supervisord started with pid 9
otrs_1       | 2017-01-03 04:22:14,294 INFO spawned: 'httpd' with pid 13
otrs_1       | 2017-01-03 04:22:14,296 INFO spawned: 'crond' with pid 14
otrs_1       | 2017-01-03 04:22:14,306 INFO spawned: 'rsyslog' with pid 15
otrs_1       | 2017-01-03 04:22:14,682 INFO exited: httpd (exit status 1; not expected)
otrs_1       | 2017-01-03 04:22:14,682 INFO received SIGCLD indicating a child quit
postfix_1    | /usr/lib/python2.7/site-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
postfix_1    |   'Supervisord is running as root and it is searching '
postfix_1    | 2017-01-03 09:22:14,905 CRIT Supervisor running as root (no user in config file)
postfix_1    | 2017-01-03 09:22:14,905 WARN Included extra file "/etc/supervisord.d/postfix.ini" during parsing
postfix_1    | Unlinking stale socket /var/tmp/supervisor.sock
postfix_1    | 2017-01-03 09:22:15,238 INFO RPC interface 'supervisor' initialized
postfix_1    | 2017-01-03 09:22:15,238 CRIT Server 'unix_http_server' running without any HTTP authentication checking
postfix_1    | 2017-01-03 09:22:15,239 INFO supervisord started with pid 11
otrs_1       | 2017-01-03 04:22:15,683 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
otrs_1       | 2017-01-03 04:22:15,683 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
otrs_1       | 2017-01-03 04:22:15,684 INFO spawned: 'httpd' with pid 19
otrs_1       | 2017-01-03 04:22:15,718 INFO exited: httpd (exit status 1; not expected)
otrs_1       | 2017-01-03 04:22:15,719 INFO received SIGCLD indicating a child quit
postfix_1    | 2017-01-03 09:22:16,241 INFO spawned: 'master' with pid 14
otrs_1       | Can't locate Encode/Locale.pm in @INC (@INC contains: /opt/otrs/Custom /opt/otrs/Kernel/cpan-lib /opt/otrs /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at Kernel/System/Encode.pm line 15.
otrs_1       | BEGIN failed--compilation aborted at Kernel/System/Encode.pm line 15.
otrs_1       | Compilation failed in require at Kernel/System/ObjectManager.pm line 29.
otrs_1       | BEGIN failed--compilation aborted at Kernel/System/ObjectManager.pm line 29.
otrs_1       | Compilation failed in require at /opt/otrs/bin/otrs.Daemon.pl line 35.
otrs_1       | BEGIN failed--compilation aborted at /opt/otrs/bin/otrs.Daemon.pl line 35.
postfix_1    | 2017-01-03 09:22:17,243 INFO success: master entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
postfix_1    | 2017-01-03 09:22:17,253 INFO exited: master (exit status 1; not expected)
otrs_1       | 2017-01-03 04:22:17,722 INFO spawned: 'httpd' with pid 23
otrs_1       | 2017-01-03 04:22:17,755 INFO exited: httpd (exit status 1; not expected)
otrs_1       | 2017-01-03 04:22:17,755 INFO received SIGCLD indicating a child quit
otrs_1       | 2017-01-03 04:22:20,759 INFO spawned: 'httpd' with pid 24
otrs_1       | 2017-01-03 04:22:20,793 INFO exited: httpd (exit status 1; not expected)
otrs_1       | 2017-01-03 04:22:20,793 INFO received SIGCLD indicating a child quit
otrs_1       | 2017-01-03 04:22:21,794 INFO gave up: httpd entered FATAL state, too many start retries too quickly

**Comment by juanluisbaptiste** [comment]
Did you try what I said before ?

**Comment by vijaykhurana** [comment]
The permissions are correct  as explained in the README. Volumes/mysql is owned by id 27 and volumes/config is owned by id 500 and group id 48.

**Comment by juanluisbaptiste** [comment]
The error is because the otrs container can't access the host mount of /opt/otrs, thus not finding the configuration files.
