### ISSUE TITLE
Include spamassassin

### ISSUE THREAD

**Issue by hos-ftv** [juanluisbaptiste/docker-otrs#61]
Hi there,

would it be possible to include [spamassassin](https://spamassassin.apache.org/)? There is a setting (i didn't know of) in `Core::Email::PostMaster` which we like to use.
So if you agree that this would be a benefit to this project I would create a pull request.

Kind Regards

**Comment by juanluisbaptiste** [comment]
Hi,

Not for now, but you could add a spamassasin container to the docker-compose.yml file and configure OTRS to use it, I think that shuld be it.

**Comment by hos-ftv** [comment]
Alright. I'm fine with an external solution.

**Comment by juanluisbaptiste** [comment]
@hos-ftv at the end did you work on this ?

**Comment by hos-ftv** [comment]
Nope. For us it was a little bit of overhead to setup an additional image just for spamassassin and to deal with the accessibility and configuration via OTRS. Maybe if we would have used it for other services/environments an extraction would make sense (for us).
We stick to the build-in - solution and use a forked version of docker-otrs. It's quite straight-forward to just add spamassassin.

Anyway. I'm totally fine with your point of view to keep this project-repo clean and to provide additional services via additional containers.

**Comment by juanluisbaptiste** [comment]
Could you share what you did anyway ? it would help me on integrating an external container, I have no experience with spamassassin.

Thanks.

**Comment by hos-ftv** [comment]
If you ship this with the docker-otrs there is not much to be done. Just install spamassassin und activate the default setting in `Core::Email::PostMaster::PreFilterModule###6-SpamAssassin`.

I've prepared a simple example-branch based on your current HEAD for a slight simpler comparison. Hope this will help:
https://github.com/juanluisbaptiste/docker-otrs/compare/master...FutureTVGroup:examples/spamassassin

**Comment by sjal** [comment]
@juanluisbaptiste I've got it working with spamassassin, if implemented correctly, would it be a feature you could merge into the master?

**Comment by juanluisbaptiste** [comment]
If your implementation adds spamassasin to this container then no, spamassasin should run on it's own container and on OTRS there should be only the code and env vars to enable this feature.

**Comment by sjal** [comment]
> If your implementation adds spamassasin to this container then no, spamassasin should run on it's own container and on OTRS there should be only the code and env vars to enable this feature.

I have it separately and I agree with you. I was supposed to tidy it up a bit for myself so once I'm done I'll surely try with a pull request here
