### ISSUE TITLE
Docker on Azure Web App: httpd stopped

### ISSUE THREAD

**Issue by xakpc** [juanluisbaptiste/docker-otrs#65]
Hi! I managed to install your docker to Azure Web App.
Everything works fine, but after some time (of inactivity probably?) I get
`Failed to load resource: the server responded with a status of 502 (Bad Gateway)` error.
It looks like httpd stopped

Could you please give me some advice about how could I resolve this issue?

Logs are below
> 2019-05-30T03:58:10.963506396Z No indexing needed! Skipping...
> 2019-05-30T03:58:10.963563298Z Done.
> 2019-05-30T03:58:11.031607235Z 
> 2019-05-30T03:58:11.031672537Z No messages available for sending.
> 2019-05-30T03:58:11.031684437Z Done.
> 2019-05-30T03:58:11.031692738Z 
> 
> 2019-05-30T03:59:11.930789333Z No indexing needed! Skipping...
> 2019-05-30T03:59:11.930831935Z Done.
> 2019-05-30T03:59:11.999063578Z 
> 2019-05-30T03:59:11.999100579Z No messages available for sending.
> 2019-05-30T03:59:11.999110480Z Done.
> 2019-05-30T03:59:11.999119080Z 
> 
> 2019-05-30T04:00:13.294109098Z No indexing needed! Skipping...
> 2019-05-30T04:00:13.294150199Z Done.
> 2019-05-30T04:00:13.878813823Z 
> 2019-05-30T04:00:13.878855724Z No messages available for sending.
> 2019-05-30T04:00:13.878865925Z Done.
> 2019-05-30T04:00:13.878874525Z 
> 
> 2019-05-30T04:00:17.401850463Z 2019-05-30 04:00:17,399 INFO stopped: crond (exit status 0)
> 2019-05-30T04:00:17.491538212Z 2019-05-30 04:00:17,487 INFO stopped: rsyslog (exit status 0)
> 2019-05-30T04:00:18.144926496Z Processing ticket escalation events ...
> 2019-05-30T04:00:18.145016299Z Done.
> 2019-05-30T04:00:18.210836064Z 2019-05-30 04:00:18,210 INFO stopped: httpd (exit status 0)
>

**Comment by juanluisbaptiste** [comment]
Well, I have not used Azure web app service, but for what I can see on their site they support many programming languages like .NET, .NET Core, Java, Ruby, Node.js, PHP, or Python, but Perl is not one of them, and OTRS is written entirely in Perl.

**Comment by xakpc** [comment]
Dear @juanluisbaptiste 

Maybe you might have an idea why every day at the same time docker stops these daemons?
Can this be related to supervisord?

> 2019-05-30T04:00:17.401850463Z 2019-05-30 04:00:17,399 INFO stopped: crond (exit status 0)
> 2019-05-30T04:00:17.491538212Z 2019-05-30 04:00:17,487 INFO stopped: rsyslog (exit status 0)
> 2019-05-30T04:00:18.210836064Z 2019-05-30 04:00:18,210 INFO stopped: httpd (exit status 0)
> -
> 2019-06-05T04:00:16.869931747Z 2019-06-05 04:00:16,866 INFO stopped: crond (exit status 0)
> 2019-06-05T04:00:17.258212290Z 2019-06-05 04:00:17,257 INFO stopped: httpd (exit status 0)
> 2019-06-05T04:00:17.271327618Z 2019-06-05 04:00:17,271 INFO stopped: rsyslog (exit status 0)
> -
> 2019-06-18T04:00:11.120373378Z 2019-06-18 04:00:11,119 INFO stopped: crond (exit status 0)
> 2019-06-18T04:00:11.278638907Z 2019-06-18 04:00:11,278 INFO stopped: httpd (exit status 0)
> 2019-06-18T04:00:11.280718474Z 2019-06-18 04:00:11,280 INFO stopped: rsyslog (exit status 0)

**Comment by juanluisbaptiste** [comment]
> Well, I have not used Azure web app service, but for what I can see on their site they support many programming languages like .NET, .NET Core, Java, Ruby, Node.js, PHP, or Python, but Perl is not one of them, and OTRS is written entirely in Perl.

@xakpc did you not see my previous message ??  OTRS is written in Perl, Azure DOES NOT support Perl, so it means it WILL NOT WORK.

**Comment by xakpc** [comment]
But it works fine until httpd stops. And after app restart, it works fine again

**Comment by juanluisbaptiste** [comment]
Dude, stop being this stubborn, Azure add DOES NOT SUPPORT PERL APPLICATIONS, what do't you understand of that statement and makes you think this PERL application will work ? 

What are you trying to do do is like putting diesel into a gas car and expect it to work even when you know that cannot get it to run.

I will not answer to this nonsense ticket.

**Comment by juanluisbaptiste** [comment]
> Dude, stop being this stubborn, Azure web app DOES NOT SUPPORT PERL APPLICATIONS, what do't you understand of that statement and makes you think this PERL application will work ?
> 
> What are you trying to do do is like putting diesel into a gas car and expect it to work even when you know that cannot get it to run.
> 
> I will not answer to this nonsense ticket.
