### ISSUE TITLE
OTRS Config.pm file

### ISSUE THREAD

**Issue by Ballzer0** [juanluisbaptiste/docker-otrs#67]
would it be possible to have a "free text" field in the .env file where you could write Custom configuration, this text would be placed in the Kernel/Config.pm file in the section under the section.
```
    # ---------------------------------------------------- #
    # insert your own config settings "here"               #
    # config settings taken from Kernel/Config/Defaults.pm #
    # ---------------------------------------------------- #
```

this is not really an issue, but more of a feature request, but having this would mean that developers could preconfigure stuff like ldaps services, that are impossible to do in the SysConfig UI

**Comment by juanluisbaptiste** [comment]
Hi,

I don't think this is a good idea, it makes it very easy to break the current configuration as you would need to pass all the perl code to insert the additional settings, not just the parameter name and value.

If you need a custom Config.pm then the correct way of doing it is by creating a new image that uses this one as a base, and add your custom Config.pm file to _/kernel_, which then gets copied to /opt/otrs on container start.

**Comment by juanluisbaptiste** [comment]
Something like:

`FROM juanluisbaptiste/otrs:latest
LABEL maintainer=''xxxxxx

COPY Config.pm /Kernel'`

That's it.
