### ISSUE TITLE
OTRS not starting

### ISSUE THREAD

**Issue by jaydeepjc** [juanluisbaptiste/docker-otrs#7]
My Composefile is

       version: '2'
      services:
        otrs:
          image: juanluisbaptiste/otrs:latest
          ports:
          - "80:80"
          links:
          - mariadb:mariadb
          - postfix:postfix
          volumes_from:
          - data
          environment:
              MYSQL_ROOT_PASSWORD: root
              OTRS_ROOT_PASSWORD: root
              OTRS_NUMBER_GENERATOR: Date
              OTRS_LANGUAGE: es
              OTRS_POSTMASTER_FETCH_TIME: 5

        mariadb:
          image: juanluisbaptiste/otrs-mariadb:latest
          expose:
          - "3306"
          volumes_from:
          - data
          environment:
              MYSQL_ROOT_PASSWORD: root
  
        postfix:
            image: juanluisbaptiste/postfix:latest
            expose:
           - "587"
           environment:
             SMTP_SERVER: smtp.server.com
              SMTP_USERNAME: user@server.net
             SMTP_PASSWORD: password@123
              SERVER_HOSTNAME: linuxdocker

         #  nginx:
         #   image: juanluisbaptiste/bigbluebutton-proxy
         #    ports:
         #      - "80:80"
         #      - "443:443"
         #    volumes: 
         #     - /var/run/docker.sock:/tmp/docker.sock
         #      - "/etc/localtime:/etc/localtime:ro"

        data:
           image: centos/mariadb:latest
           volumes:
           #- "./db:/var/lib/mysql"
           - /var/lib/mysql"
           - "./otrs/backup:/var/otrs/backups"
           - "./volumes/config:/opt/otrs/Kernel"
           - "/etc/localtime:/etc/localtime:ro"
           command: /bin/true

Output is 

      docker-compose up
      Creating otrsrel501_postfix_1
      Creating otrsrel501_data_1
      Creating otrsrel501_mariadb_1
       Creating otrsrel501_otrs_1
      Attaching to otrsrel501_postfix_1, otrsrel501_data_1, otrsrel501_mariadb_1, otrsrel501_otrs_1
      mariadb_1  | Running mysql_install_db ...
      mariadb_1  | Installing MariaDB/MySQL system tables in '/var/lib/mysql' ...
      otrsrel501_data_1 exited with code 0
      otrs_1     | [INFO] ERROR
       otrs_1     | [WARNING] DB server still isn't up, sleeping a little bit ...
      mariadb_1  | 170131 16:51:02 [Note] /usr/libexec/mysqld (mysqld 5.5.52-MariaDB) starting as process      28 ...
      mariadb_1  | OK
      mariadb_1  | Filling help tables...
       mariadb_1  | 170131 16:51:03 [Note] /usr/libexec/mysqld (mysqld 5.5.52-MariaDB) starting as  process 37 ...
      postfix_1  | postmap: fatal: bad string length 0 < 1: mydomain =
      mariadb_1  | OK
       mariadb_1  |
      mariadb_1  | To start mysqld at boot time you have to copy
       mariadb_1  | support-files/mysql.server to the right place for your system
      mariadb_1  |
       mariadb_1  | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
      mariadb_1  | To do so, start the server, then issue the following commands:
      mariadb_1  |
       mariadb_1  | '/usr/bin/mysqladmin' -u root password 'new-password'
       mariadb_1  | '/usr/bin/mysqladmin' -u root -h b9a40aabad25 password 'new-password'
       mariadb_1  |
        mariadb_1  | Alternatively you can run:
        mariadb_1  | '/usr/bin/mysql_secure_installation'
        mariadb_1  |
        mariadb_1  | which will also give you the option of removing the test
        mariadb_1  | databases and anonymous user created by default.  This is
        mariadb_1  | strongly recommended for production servers.
        mariadb_1  |
        mariadb_1  | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
        mariadb_1  | MySQL manual for more instructions.
        mariadb_1  |
        mariadb_1  | You can start the MariaDB daemon with:
        mariadb_1  | cd '/usr' ; /usr/bin/mysqld_safe --datadir='/var/lib/mysql'
        mariadb_1  |
        mariadb_1  | You can test the MariaDB daemon with mysql-test-run.pl
        mariadb_1  | cd '/usr/mysql-test' ; perl mysql-test-run.pl
        mariadb_1  |
        mariadb_1  | Please report any problems at http://mariadb.org/jira
        mariadb_1  |
        mariadb_1  | The latest information about MariaDB is available at http://mariadb.org/.
        mariadb_1  | You can find additional information about the MySQL part at:
        mariadb_1  | http://dev.mysql.com
        mariadb_1  | Support MariaDB development by buying support/new features from MariaDB
        mariadb_1  | Corporation Ab. You can contact us about this at sales@mariadb.com.
        mariadb_1  | Alternatively consider joining our community based development effort:
        mariadb_1  | http://mariadb.com/kb/en/contributing-to-the-mariadb-project/
        mariadb_1  |
        mariadb_1  | Finished mysql_install_db
        mariadb_1  | 170131 16:51:03 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
       mariadb_1  | 170131 16:51:04 mysqld_safe Starting mysqld daemon with databases from   /var/lib/mysql
        otrs_1     | [INFO] ERROR
        otrs_1     | [WARNING] DB server still isn't up, sleeping a little bit ...
        postfix_1  | /usr/lib/python2.7/site-packages/supervisor/options.py:295: UserWarning: Supervisord   is running as root and it is searching for its configuration file in default locations (including its current   working directory); you probably want to specify a "-c" argument specifying an absolute path to a   configuration file for improved security.
         postfix_1  |   'Supervisord is running as root and it is searching '
         postfix_1  | 2017-01-31 11:21:04,954 CRIT Supervisor running as root (no user in config file)
         postfix_1  | 2017-01-31 11:21:04,958 WARN Included extra file "/etc/supervisord.d/postfix.ini" during parsing
         postfix_1  | 2017-01-31 11:21:05,119 INFO RPC interface 'supervisor' initialized
         postfix_1  | 2017-01-31 11:21:05,135 CRIT Server 'unix_http_server' running without any HTTP  authentication checking
         postfix_1  | 2017-01-31 11:21:05,136 INFO supervisord started with pid 11
         postfix_1  | 2017-01-31 11:21:06,155 INFO spawned: 'master' with pid 14
         postfix_1  | 2017-01-31 11:21:07,191 INFO success: master entered RUNNING state, process has   stayed up for > than 0 seconds (startsecs)
         otrs_1     | [INFO] ERROR
        otrs_1     | [WARNING] DB server still isn't up, sleeping a little bit ...
        postfix_1  | 2017-01-31 11:21:08,542 INFO exited: master (exit status 1; not expected)
         otrs_1     | [INFO] ERROR
        otrs_1     | [WARNING] DB server still isn't up, sleeping a little bit ...
         otrs_1     | [INFO] ERROR
         otrs_1     | [WARNING] DB server still isn't up, sleeping a little bit ...
         otrs_1     | [INFO] ERROR
         otrs_1     | [WARNING] DB server still isn't up, sleeping a little bit ...
         otrs_1     | [INFO] ERROR

**Comment by juanluisbaptiste** [comment]
Did you check host volume directory permissions as described on the README file ?

**Comment by juanluisbaptiste** [comment]
Closing for lack of response.
