### ISSUE TITLE
Make otrs ftp url be configurable

### ISSUE THREAD

**Issue by glmars** [juanluisbaptiste/docker-otrs#70]
Can we introduce an environment variable for this?

Something like that might be good:
```
ENV OTRS_DOWNLOAD_MIRROR "http://ftp.otrs.org/pub/otrs"
...
yum install -y ${OTRS_DOWNLOAD_MIRROR}/RPMS/rhel/7/otrs-${OTRS_VERSION}.noarch.rpm
```

Sometimes it’s more convenient to use a local mirror to load OTRS

**Comment by juanluisbaptiste** [comment]
PR welcome.

**Comment by glmars** [comment]
Ok. I going to make some (I should test it before commit, but I newbie in OTRS and I never install it before :smile:)

**Comment by juanluisbaptiste** [comment]
As it seems you don't have the time to finish this I'm going to close it. Reopen if you do complete.
