### ISSUE TITLE
docker-compose up is not working out of the box

### ISSUE THREAD

**Issue by pavelsr** [juanluisbaptiste/docker-otrs#77]
Possible solutions:

1) Change from `OTRS_DB_USER=otrs` to `OTRS_DB_USER=root`

or

2) Set `MYSQL_USER=otrs` and `MYSQL_PASSWORD=changeme`

at [.env.example](https://github.com/juanluisbaptiste/docker-otrs/blob/master/.env.example)

**Comment by juanluisbaptiste** [comment]
I'm not interested on having an out of the box experience, there are too much parameters to configure that this is really not posiible. Also your message does not say anything of what's not working out of the box nor do you explain your proposed solution.
