### ISSUE TITLE
High RAM Load & Killing Kernel Deamon

### ISSUE THREAD

**Issue by AxeKR** [juanluisbaptiste/docker-otrs#83]
Hi,

we are trying out your docker workflow. After 
sudo docker-compose -f docker-compose-prod.yml up

the process is hung up with tryiing to kill

otrs_1     | Killing Kernel::System::Daemon::DaemonModules::SystemConfigurationSyncManager with PID 87

The RAM Load is very high. System ist ubuntu 18.04.4 fresh install

**Comment by juanluisbaptiste** [comment]
Hi,

Probably your host does not have enough memory to run the container. Also as the new issue instructions says you need to post log output, env file and docker-copmose contents so we can debug the issue.

**Comment by juanluisbaptiste** [comment]
Hi,

Probably your host does not have enough memory to run the container. Also as the new issue instructions says you need to post log output, env file and docker-copmose contents so we can debug the issue.

**Comment by juanluisbaptiste** [comment]
Closing for lack of answer.
