### ISSUE TITLE
Couldn't find env file

### ISSUE THREAD

**Issue by roskogabor** [juanluisbaptiste/docker-otrs#85]
**Describe the issue**
I cloned the repo and followed the instructions.
cd to docker-otrs and tried to build with docker-compose:

$ cd docker-otrs/
$ sudo docker-compose build
ERROR: Couldn't find env file: /home/ansi/docker-otrs/.env

**Expected behavior**
Docker pull and build images.

**What happened**
Docker-compose need env file.

What should I do or what I do wrong?

**Comment by AxeKR** [comment]
hi, did you edit the example.env file? 
Have a look at docker-otrs. there should be a example file which must be edited and saved as .env

**Comment by roskogabor** [comment]
@AxeKR This is what I have in the folder:
$ ls -1
CHANGELOG.md
docker-compose-prod.yml
docker-compose.yml
img
launch-testing.sh
LICENSE
mariadb
otrs
otrs.service
README.md

Is the otrs.service the example file? Sorry if my question is dumb Im new to the docker world.

**Comment by juanluisbaptiste** [comment]
As @AxeKR said, you need to rename the .env.example file to .env.

For usage questions please use the official OTRS forums, not this issue tracker.
