### ISSUE TITLE
How to send mail configuration?

### ISSUE THREAD

**Issue by hom7** [juanluisbaptiste/docker-otrs#88]
![image](https://user-images.githubusercontent.com/15682396/79099183-3078a200-7d96-11ea-8a46-37d5593e99c0.png)

![image](https://user-images.githubusercontent.com/15682396/79099224-48e8bc80-7d96-11ea-96e8-299e31edd08c.png)

Seems to be successful, but unable to send mail

**Comment by juanluisbaptiste** [comment]
Hi,

You completey skipped the bug reporting instructions, please add the requested information and I will reopen this when you do. Those instructions are there to ease debugging of the issues.

**Comment by hom7** [comment]
docker postfix reports error "postfix_1 | SMTP_SERVER is not set"
I don't know how to set up smtp_server, but I'm sure it is configured in .env.
I re-built an additional postfix, which can send mail system normally.

There is still a problem with otrs sending emails, and there are no special logs.

![image](https://user-images.githubusercontent.com/15682396/79180982-e945ec00-7e3d-11ea-877c-df4641bd9a67.png)
![image](https://user-images.githubusercontent.com/15682396/79181018-fb278f00-7e3d-11ea-9ded-66176def2a6a.png)
