### ISSUE TITLE
[FEATURE REQUEST] mariadb: innodb_buffer_pool_size as variable

### ISSUE THREAD

**Issue by rdxmb** [juanluisbaptiste/docker-otrs#93]
My full index search had a duration for about 3-5 minutes.
Increasing the `innodb_buffer_pool_size` fixed that. So I need this changeable.

Can we implement INNODB_BUFFER_POOL_SIZE as a variable and write it on runtime to the config?

` echo "innodb_buffer_pool_size=${INNODB_BUFFER_POOL_SIZE}" >> /etc/mysql/conf.d/otrs.cnf`

**Comment by rdxmb** [comment]
As a workaround, I will mount another file withing `/etc/mysql/conf.d/`

**Comment by juanluisbaptiste** [comment]
If I do this it would be for all recommended parameters, but for now I do not have the time to do it, and as you say you can mount your own configuration file set as you need.

Sometimes I think if I should remove this image so upstream images can be used and configured as needed by each user.

**Comment by rdxmb** [comment]
> Sometimes I think if I should remove this image so upstream images can be used and configured as needed by each user.

If you add the recommended my.cnf-Parameters to the README on docker hub, I do not see any problem with this.

**Comment by juanluisbaptiste** [comment]
> > Sometimes I think if I should remove this image so upstream images can be used and configured as needed by each user.
> 
> If you add the recommended my.cnf-Parameters to the README on docker hub, I do not see any problem with this.

They are already  in the README file on docker hub.

**Comment by rdxmb** [comment]
> They are already in the README file on docker hub.

Yes, but in the README of the mariadb image. If this is deprecated, the my.cnf-Parameters could/should(?) be in https://hub.docker.com/r/juanluisbaptiste/otrs/ instead of

`We also include a MariaDB Dockerfile for a pre-configured image with the required database settings.`
